//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;

namespace Highlander.Metadata.Common {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/CoreObjects.xsd", IsNullable=false)]
    public partial class UserGroup : CoreObject {
        
        private bool disabledField;
        
        private string groupNameField;
        
        private string fullNameField;
        
        private string[] memberUsersField;
        
        private string[] memberGroupsField;
        
        /// <remarks/>
        public bool Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("MemberUsers")]
        public string[] MemberUsers {
            get {
                return this.memberUsersField;
            }
            set {
                this.memberUsersField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("MemberGroups")]
        public string[] MemberGroups {
            get {
                return this.memberGroupsField;
            }
            set {
                this.memberGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(AlertSignal))]
    [XmlInclude(typeof(RuleObject))]
    [XmlInclude(typeof(AlertRule))]
    [XmlInclude(typeof(UserGroup))]
    [XmlInclude(typeof(UserDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    public partial class CoreObject {
    }
    
    /// <remarks/>
    [XmlInclude(typeof(AlertRule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    public partial class RuleObject : CoreObject {
        
        private int priorityField;
        
        private bool disabledField;
        
        private string hostEnvAbbrField;
        
        private string hostComputerField;
        
        private string hostInstanceField;
        
        private string hostUserNameField;
        
        private string ruleUniqueIdField;
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string HostEnvAbbr {
            get {
                return this.hostEnvAbbrField;
            }
            set {
                this.hostEnvAbbrField = value;
            }
        }
        
        /// <remarks/>
        public string HostComputer {
            get {
                return this.hostComputerField;
            }
            set {
                this.hostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string HostInstance {
            get {
                return this.hostInstanceField;
            }
            set {
                this.hostInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string HostUserName {
            get {
                return this.hostUserNameField;
            }
            set {
                this.hostUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string RuleUniqueId {
            get {
                return this.ruleUniqueIdField;
            }
            set {
                this.ruleUniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    public partial class UserDetail : CoreObject {
        
        private bool disabledField;
        
        private string userNameField;
        
        private string fullNameField;
        
        private string windowsLoginIdField;
        
        private string windowsDomainField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public bool Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string WindowsLoginId {
            get {
                return this.windowsLoginIdField;
            }
            set {
                this.windowsLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public string WindowsDomain {
            get {
                return this.windowsDomainField;
            }
            set {
                this.windowsDomainField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/CoreObjects.xsd", IsNullable=false)]
    public partial class CoreAlertRule : RuleObject {
        
        private string dataItemKindField;
        
        private string dataTypeNameField;
        
        private string dataSubsExprField;
        
        private string constraintField;
        
        private string conditionField;
        
        private string alertPropertiesField;
        
        private string monitorPeriodField;
        
        private string publishPeriodField;
        
        private string signalFormatField;
        
        /// <remarks/>
        public string DataItemKind {
            get {
                return this.dataItemKindField;
            }
            set {
                this.dataItemKindField = value;
            }
        }
        
        /// <remarks/>
        public string DataTypeName {
            get {
                return this.dataTypeNameField;
            }
            set {
                this.dataTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string DataSubsExpr {
            get {
                return this.dataSubsExprField;
            }
            set {
                this.dataSubsExprField = value;
            }
        }
        
        /// <remarks/>
        public string Constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
        
        /// <remarks/>
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string AlertProperties {
            get {
                return this.alertPropertiesField;
            }
            set {
                this.alertPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public string MonitorPeriod {
            get {
                return this.monitorPeriodField;
            }
            set {
                this.monitorPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string PublishPeriod {
            get {
                return this.publishPeriodField;
            }
            set {
                this.publishPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string SignalFormat {
            get {
                return this.signalFormatField;
            }
            set {
                this.signalFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CoreObjects.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/CoreObjects.xsd", IsNullable=false)]
    public partial class CoreAlertSignal : CoreObject {
        
        private string ruleUniqueIdField;
        
        private string alertServerField;
        
        private string statusField;
        
        private string signalMessageField;
        
        private string lastMonitoredField;
        
        /// <remarks/>
        public string RuleUniqueId {
            get {
                return this.ruleUniqueIdField;
            }
            set {
                this.ruleUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string AlertServer {
            get {
                return this.alertServerField;
            }
            set {
                this.alertServerField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string SignalMessage {
            get {
                return this.signalMessageField;
            }
            set {
                this.signalMessageField = value;
            }
        }
        
        /// <remarks/>
        public string LastMonitored {
            get {
                return this.lastMonitoredField;
            }
            set {
                this.lastMonitoredField = value;
            }
        }
    }
}
