//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;

namespace Highlander.Metadata.Common {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://tempuri.org/SubscriptionFormat.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/SubscriptionFormat.xsd", IsNullable=false)]
    public partial class ClientSubscriptionState {
        
        private string connectionIdField;
        
        private string subscriptionIdField;
        
        private string expiryTimeField;
        
        private string dataTypeNameField;
        
        private int itemKindField;
        
        private string expressionField;
        
        private string[] appScopesField;
        
        private long minimumUSNField;
        
        private bool excludeExistingField;
        
        private bool includeDeletedField;
        
        private string asAtTimeField;
        
        private bool excludeDataBodyField;
        
        private bool debugRequestField;
        
        /// <remarks/>
        public string ConnectionId {
            get {
                return this.connectionIdField;
            }
            set {
                this.connectionIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DataTypeName {
            get {
                return this.dataTypeNameField;
            }
            set {
                this.dataTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int ItemKind {
            get {
                return this.itemKindField;
            }
            set {
                this.itemKindField = value;
            }
        }
        
        /// <remarks/>
        public string Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("AppScopes")]
        public string[] AppScopes {
            get {
                return this.appScopesField;
            }
            set {
                this.appScopesField = value;
            }
        }
        
        /// <remarks/>
        public long MinimumUSN {
            get {
                return this.minimumUSNField;
            }
            set {
                this.minimumUSNField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcludeExisting {
            get {
                return this.excludeExistingField;
            }
            set {
                this.excludeExistingField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeDeleted {
            get {
                return this.includeDeletedField;
            }
            set {
                this.includeDeletedField = value;
            }
        }
        
        /// <remarks/>
        public string AsAtTime {
            get {
                return this.asAtTimeField;
            }
            set {
                this.asAtTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcludeDataBody {
            get {
                return this.excludeDataBodyField;
            }
            set {
                this.excludeDataBodyField = value;
            }
        }
        
        /// <remarks/>
        public bool DebugRequest {
            get {
                return this.debugRequestField;
            }
            set {
                this.debugRequestField = value;
            }
        }
    }
}
