//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace FpML.V5r10.Codes
{
}

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class schemeDefinitions {
    
    private schemeDefinitionsScheme[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("scheme", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public schemeDefinitionsScheme[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class schemeDefinitionsScheme {
    
    private schemeDefinitionsSchemeSchemeValues[] schemeValuesField;
    
    private string nameField;
    
    private string uriField;
    
    private string sourceField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("schemeValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public schemeDefinitionsSchemeSchemeValues[] schemeValues {
        get {
            return this.schemeValuesField;
        }
        set {
            this.schemeValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class schemeDefinitionsSchemeSchemeValues {
    
    private schemeDefinitionsSchemeSchemeValuesSchemeValue[] schemeValueField;
    
    private schemeDefinitionsSchemeSchemeValuesSchemevalue[] schemevalueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("schemeValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public schemeDefinitionsSchemeSchemeValuesSchemeValue[] schemeValue {
        get {
            return this.schemeValueField;
        }
        set {
            this.schemeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Schemevalue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public schemeDefinitionsSchemeSchemeValuesSchemevalue[] Schemevalue {
        get {
            return this.schemevalueField;
        }
        set {
            this.schemevalueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class schemeDefinitionsSchemeSchemeValuesSchemeValue {
    
    private string nameField;
    
    private string captionField;
    
    private string descriptionField;
    
    private string dcbField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string caption {
        get {
            return this.captionField;
        }
        set {
            this.captionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dcb {
        get {
            return this.dcbField;
        }
        set {
            this.dcbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class schemeDefinitionsSchemeSchemeValuesSchemevalue {
    
    private string captionField;
    
    private string nameField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string caption {
        get {
            return this.captionField;
        }
        set {
            this.captionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}
