//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Highlander.EquityCalculator.TestData.V5r3
{

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.1432.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/StockFormat.xsd", IsNullable = false)]
    public partial class Stock
    {

        private string nameField;

        private string assetIdField;

        private decimal spotField;

        private bool spotFieldSpecified;

        private string dateField;

        private StockDividend[] dividendsField;

        private StockRateCurve rateCurveField;

        private StockVolatilitySurface volatilitySurfaceField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string AssetId
        {
            get
            {
                return this.assetIdField;
            }
            set
            {
                this.assetIdField = value;
            }
        }

        /// <remarks/>
        public decimal Spot
        {
            get
            {
                return this.spotField;
            }
            set
            {
                this.spotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpotSpecified
        {
            get
            {
                return this.spotFieldSpecified;
            }
            set
            {
                this.spotFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dividend", IsNullable = false)]
        public StockDividend[] Dividends
        {
            get
            {
                return this.dividendsField;
            }
            set
            {
                this.dividendsField = value;
            }
        }

        /// <remarks/>
        public StockRateCurve RateCurve
        {
            get
            {
                return this.rateCurveField;
            }
            set
            {
                this.rateCurveField = value;
            }
        }

        /// <remarks/>
        public StockVolatilitySurface VolatilitySurface
        {
            get
            {
                return this.volatilitySurfaceField;
            }
            set
            {
                this.volatilitySurfaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockDividend
    {

        private string exDateField;

        private decimal amountField;

        private bool amountFieldSpecified;

        private string priceUnitsField;

        /// <remarks/>
        public string ExDate
        {
            get
            {
                return this.exDateField;
            }
            set
            {
                this.exDateField = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PriceUnits
        {
            get
            {
                return this.priceUnitsField;
            }
            set
            {
                this.priceUnitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockRateCurve
    {

        private string baseDateField;

        private string ccyField;

        private string[] dateArrayField;

        private double[] rateArrayField;

        private string rateTypeField;

        /// <remarks/>
        public string BaseDate
        {
            get
            {
                return this.baseDateField;
            }
            set
            {
                this.baseDateField = value;
            }
        }

        /// <remarks/>
        public string Ccy
        {
            get
            {
                return this.ccyField;
            }
            set
            {
                this.ccyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateArray")]
        public string[] DateArray
        {
            get
            {
                return this.dateArrayField;
            }
            set
            {
                this.dateArrayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RateArray")]
        public double[] RateArray
        {
            get
            {
                return this.rateArrayField;
            }
            set
            {
                this.rateArrayField = value;
            }
        }

        /// <remarks/>
        public string RateType
        {
            get
            {
                return this.rateTypeField;
            }
            set
            {
                this.rateTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockVolatilitySurface
    {

        private string stockIdField;

        private string isCompleteField;

        private StockVolatilitySurfaceForwardExpiry[] expiriesField;

        /// <remarks/>
        public string StockId
        {
            get
            {
                return this.stockIdField;
            }
            set
            {
                this.stockIdField = value;
            }
        }

        /// <remarks/>
        public string IsComplete
        {
            get
            {
                return this.isCompleteField;
            }
            set
            {
                this.isCompleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ForwardExpiry", IsNullable = false)]
        public StockVolatilitySurfaceForwardExpiry[] Expiries
        {
            get
            {
                return this.expiriesField;
            }
            set
            {
                this.expiriesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockVolatilitySurfaceForwardExpiry
    {

        private string expiryDateField;

        private decimal fwdPriceField;

        private bool fwdPriceFieldSpecified;

        private string nodalPointField;

        private StockVolatilitySurfaceForwardExpiryStrike[] strikesField;

        /// <remarks/>
        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        public decimal FwdPrice
        {
            get
            {
                return this.fwdPriceField;
            }
            set
            {
                this.fwdPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FwdPriceSpecified
        {
            get
            {
                return this.fwdPriceFieldSpecified;
            }
            set
            {
                this.fwdPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NodalPoint
        {
            get
            {
                return this.nodalPointField;
            }
            set
            {
                this.nodalPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Strike", IsNullable = false)]
        public StockVolatilitySurfaceForwardExpiryStrike[] Strikes
        {
            get
            {
                return this.strikesField;
            }
            set
            {
                this.strikesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockVolatilitySurfaceForwardExpiryStrike
    {

        private double moneynessField;

        private bool moneynessFieldSpecified;

        private double strikePriceField;

        private bool strikePriceFieldSpecified;

        private StockVolatilitySurfaceForwardExpiryStrikeVolatility volatilityField;

        private string volatilityHasBeenSetField;

        /// <remarks/>
        public double Moneyness
        {
            get
            {
                return this.moneynessField;
            }
            set
            {
                this.moneynessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoneynessSpecified
        {
            get
            {
                return this.moneynessFieldSpecified;
            }
            set
            {
                this.moneynessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double StrikePrice
        {
            get
            {
                return this.strikePriceField;
            }
            set
            {
                this.strikePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrikePriceSpecified
        {
            get
            {
                return this.strikePriceFieldSpecified;
            }
            set
            {
                this.strikePriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public StockVolatilitySurfaceForwardExpiryStrikeVolatility Volatility
        {
            get
            {
                return this.volatilityField;
            }
            set
            {
                this.volatilityField = value;
            }
        }

        /// <remarks/>
        public string VolatilityHasBeenSet
        {
            get
            {
                return this.volatilityHasBeenSetField;
            }
            set
            {
                this.volatilityHasBeenSetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/StockFormat.xsd")]
    public partial class StockVolatilitySurfaceForwardExpiryStrikeVolatility
    {

        private decimal valueField;

        private bool valueFieldSpecified;

        /// <remarks/>
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
}