//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLV5r3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HLV5r3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; is not in the cache..
        /// </summary>
        internal static string ErrorCacheItemNotFound {
            get {
                return ResourceManager.GetString("ErrorCacheItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache key cannot be null or empty..
        /// </summary>
        internal static string ErrorCacheKeyInvalid {
            get {
                return ResourceManager.GetString("ErrorCacheKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string ErrorCurrencyNotRecognized {
            get {
                return ResourceManager.GetString("ErrorCurrencyNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary based properties are not available..
        /// </summary>
        internal static string ErrorDictionaryNotSupported {
            get {
                return ResourceManager.GetString("ErrorDictionaryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ErrorHolidaysArgumentNotSupported {
            get {
                return ResourceManager.GetString("ErrorHolidaysArgumentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property accessor type. Indexer based properties are not available..
        /// </summary>
        internal static string ErrorIndexerNotSupported {
            get {
                return ResourceManager.GetString("ErrorIndexerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument type &apos;{0}&apos; is not handled..
        /// </summary>
        internal static string ErrorInstrumentTypeNotHandled {
            get {
                return ResourceManager.GetString("ErrorInstrumentTypeNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation method &apos;{0}&apos; is not recognised..
        /// </summary>
        internal static string ErrorInterpolationMethodNotRecognized {
            get {
                return ResourceManager.GetString("ErrorInterpolationMethodNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is either a enumerated value or not present..
        /// </summary>
        internal static string ErrorInvalidObjectKey {
            get {
                return ResourceManager.GetString("ErrorInvalidObjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter cannot be null..
        /// </summary>
        internal static string ErrorNoItemName {
            get {
                return ResourceManager.GetString("ErrorNoItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property: {0} is not part of the object: {1}..
        /// </summary>
        internal static string ErrorObjectPropertyNotFound {
            get {
                return ResourceManager.GetString("ErrorObjectPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object: {0} is not present in the Object Cache..
        /// </summary>
        internal static string ErrorUnknownObjectName {
            get {
                return ResourceManager.GetString("ErrorUnknownObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property: {0} is not part of the object: {1}..
        /// </summary>
        internal static string ErrorUnknownPropertyName {
            get {
                return ResourceManager.GetString("ErrorUnknownPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no log messages..
        /// </summary>
        internal static string MessageLogEmpty {
            get {
                return ResourceManager.GetString("MessageLogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log is currently inactive..
        /// </summary>
        internal static string MessageLogInactive {
            get {
                return ResourceManager.GetString("MessageLogInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1a.
        /// </summary>
        internal static string QVersion {
            get {
                return ResourceManager.GetString("QVersion", resourceCulture);
            }
        }
    }
}
