//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Orion.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TradeImportRuleFormat.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TradeImportRuleFormat.xsd", IsNullable=false)]
    public partial class TradeImportRule {
        
        private int priorityField;
        
        private bool disabledField;
        
        private string hostEnvNameField;
        
        private string hostComputerField;
        
        private string hostInstanceField;
        
        private string hostUserNameField;
        
        private string ruleNameField;
        
        private string includeCounterpartyIdsField;
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string hostEnvName {
            get {
                return this.hostEnvNameField;
            }
            set {
                this.hostEnvNameField = value;
            }
        }
        
        /// <remarks/>
        public string hostComputer {
            get {
                return this.hostComputerField;
            }
            set {
                this.hostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string hostInstance {
            get {
                return this.hostInstanceField;
            }
            set {
                this.hostInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string hostUserName {
            get {
                return this.hostUserNameField;
            }
            set {
                this.hostUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        public string IncludeCounterpartyIds {
            get {
                return this.includeCounterpartyIdsField;
            }
            set {
                this.includeCounterpartyIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TradeImportRuleFormat.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TradeImportRuleFormat.xsd", IsNullable=false)]
    public partial class TradeImportRuleSet {
        
        private string defaultHostEnvNameField;
        
        private string defaultHostComputerField;
        
        private string defaultIncludeCounterpartyIdsField;
        
        private TradeImportRule[] tradeImportRuleField;
        
        /// <remarks/>
        public string defaultHostEnvName {
            get {
                return this.defaultHostEnvNameField;
            }
            set {
                this.defaultHostEnvNameField = value;
            }
        }
        
        /// <remarks/>
        public string defaultHostComputer {
            get {
                return this.defaultHostComputerField;
            }
            set {
                this.defaultHostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string defaultIncludeCounterpartyIds {
            get {
                return this.defaultIncludeCounterpartyIdsField;
            }
            set {
                this.defaultIncludeCounterpartyIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TradeImportRule")]
        public TradeImportRule[] TradeImportRule {
            get {
                return this.tradeImportRuleField;
            }
            set {
                this.tradeImportRuleField = value;
            }
        }
    }
}
