//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurveEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurveEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PricingStructureTypes&gt;
        ///  &lt;PricingStructureType id=&quot;RateSpreadCurve&quot;&gt;
        ///    &lt;Algorithms&gt;
        ///      &lt;!-- Calypso --&gt;
        ///      &lt;Algorithm id=&quot;CalypsoAlgo4&quot;&gt;
        ///        &lt;Properties&gt;
        ///          &lt;Property name=&quot;Tolerance&quot;&gt;1E-10&lt;/Property&gt;
        ///          &lt;Property name=&quot;Bootstrapper&quot;&gt;FastBootstrapper&lt;/Property&gt;
        ///          &lt;Property name=&quot;BootstrapperInterpolation&quot;&gt;LinearRateInterpolation&lt;/Property&gt;
        ///          &lt;Property name=&quot;CurveInterpolation&quot;&gt;LinearInterpolation&lt;/Property&gt;
        ///          &lt;Property name=&quot;UnderlyingCurve&quot;&gt;ZeroC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PricingStructureAlgorithms {
            get {
                return ResourceManager.GetString("PricingStructureAlgorithms", resourceCulture);
            }
        }
    }
}
