//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;

namespace Core.Common {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://tempuri.org/DebugFormat.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/DebugFormat.xsd", IsNullable=false)]
    public partial class DebugTraceEvent {
        
        private string traceNameField;
        
        private string idField;
        
        private string nodeIdField;
        
        private string hostNameField;
        
        private string userNameField;
        
        private string applNameField;
        
        private string instanceField;
        
        private System.DateTime arrivedUtcField;
        
        private string otherInfoField;
        
        /// <remarks/>
        public string TraceName {
            get {
                return this.traceNameField;
            }
            set {
                this.traceNameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplName {
            get {
                return this.applNameField;
            }
            set {
                this.applNameField = value;
            }
        }
        
        /// <remarks/>
        public string Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ArrivedUtc {
            get {
                return this.arrivedUtcField;
            }
            set {
                this.arrivedUtcField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInfo {
            get {
                return this.otherInfoField;
            }
            set {
                this.otherInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://tempuri.org/DebugFormat.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/DebugFormat.xsd", IsNullable=false)]
    public partial class DebugCacheStats {
        
        private string hostNameField;
        
        private string userWNIdField;
        
        private string applNameField;
        
        private string nodeIdField;
        
        private string origEnvField;
        
        private string rTVersionField;
        
        private string rTPubKeyField;
        
        private string updatedField;
        
        private string countersField;
        
        /// <remarks/>
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserWNId {
            get {
                return this.userWNIdField;
            }
            set {
                this.userWNIdField = value;
            }
        }
        
        /// <remarks/>
        public string ApplName {
            get {
                return this.applNameField;
            }
            set {
                this.applNameField = value;
            }
        }
        
        /// <remarks/>
        public string NodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrigEnv {
            get {
                return this.origEnvField;
            }
            set {
                this.origEnvField = value;
            }
        }
        
        /// <remarks/>
        public string RTVersion {
            get {
                return this.rTVersionField;
            }
            set {
                this.rTVersionField = value;
            }
        }
        
        /// <remarks/>
        public string RTPubKey {
            get {
                return this.rTPubKeyField;
            }
            set {
                this.rTPubKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public string Counters {
            get {
                return this.countersField;
            }
            set {
                this.countersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://tempuri.org/DebugFormat.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/DebugFormat.xsd", IsNullable=false)]
    public partial class DebugLogEvent {
        
        private string hostNameField;
        
        private string userNameField;
        
        private string applNameField;
        
        private int processIdField;
        
        private int seqNumberField;
        
        private string origEnvField;
        
        private string createdField;
        
        private int severityField;
        
        private string messageField;
        
        /// <remarks/>
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplName {
            get {
                return this.applNameField;
            }
            set {
                this.applNameField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessId {
            get {
                return this.processIdField;
            }
            set {
                this.processIdField = value;
            }
        }
        
        /// <remarks/>
        public int SeqNumber {
            get {
                return this.seqNumberField;
            }
            set {
                this.seqNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OrigEnv {
            get {
                return this.origEnvField;
            }
            set {
                this.origEnvField = value;
            }
        }
        
        /// <remarks/>
        public string Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public int Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
