//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLV5r3.Impl
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.ExcelApi.Impl.ExcelApiResource", typeof(ExcelApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelApi - {0}.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public field or property &quot;{0}.{1}&quot; does not exist..
        /// </summary>
        internal static string ErrorClassMemberNotExist {
            get {
                return ResourceManager.GetString("ErrorClassMemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &quot;{0}.{1}&quot; not found..
        /// </summary>
        internal static string ErrorClassMethodNotFound {
            get {
                return ResourceManager.GetString("ErrorClassMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &quot;{0}&quot; not found..
        /// </summary>
        internal static string ErrorFunctionNotFound {
            get {
                return ResourceManager.GetString("ErrorFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &quot;{0}&quot; found in multiple assemblies ({1}, {2})..
        /// </summary>
        internal static string ErrorFunctionNotUnique {
            get {
                return ResourceManager.GetString("ErrorFunctionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0
        /// style=&apos;margin-left:17.6pt;border-collapse:collapse&apos;&gt;
        /// &lt;tr&gt;
        ///  &lt;td width=163 valign=top style=&apos;width:122.4pt;border:solid windowtext 1.0pt;
        ///  padding:0cm 5.4pt 0cm 5.4pt&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-top:3.0pt;margin-right:0cm;margin-bottom:
        ///  3.0pt;margin-left:0cm&apos;&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana;
        ///  color:maroon&apos;&gt;{FunctionName}&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td width=207 valign=top style=&apos;width:155.3pt;border:solid win [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorHeaderHtml {
            get {
                return ResourceManager.GetString("errorHeaderHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=ErrSection&gt;
        ///&lt;br /&gt;
        ///&lt;p class=MsoNormal style=&apos;margin-top:6.0pt;margin-right:2.85pt;margin-bottom:
        ///  6.0pt;margin-left:18.0pt&apos;&gt;&lt;b&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana;
        ///color:red&apos;&gt;{Message}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-top:6.0pt;margin-right:2.85pt;margin-bottom:
        ///  6.0pt;margin-left:18.0pt&apos;&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana&apos;&gt;{StackTrace}&lt;/span&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string ErrorHtml {
            get {
                return ResourceManager.GetString("ErrorHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value. ({0}).
        /// </summary>
        internal static string ErrorInvalidArgument {
            get {
                return ResourceManager.GetString("ErrorInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid ExcelConversionTypes.{0}&quot;.
        /// </summary>
        internal static string ErrorInvalidConversionType {
            get {
                return ResourceManager.GetString("ErrorInvalidConversionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method={0}, Name={1}, Value={2}.
        /// </summary>
        internal static string ErrorInvalidPropertyValue {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;title&gt;{Message}&lt;/title&gt;
        ///
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:Verdana;
        ///	panose-1:2 11 6 4 3 5 4 4 2 4;}
        /// /* Style Definitions */
        /// p.MsoNormal, li.MsoNormal, div.MsoNormal
        ///	{margin:0cm;
        ///	margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;;}
        ///@page ErrSection
        ///	{size:841.9pt 595.3pt;
        ///	margin:89.85pt 72.0pt 89.85pt 72.0pt;}
        ///div.ErrSection
        ///	{page:ErrSection; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorLogHtml {
            get {
                return ResourceManager.GetString("ErrorLogHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=ErrSection&gt;
        ///&lt;br /&gt;
        ///&lt;p class=MsoNormal style=&apos;margin-top:6.0pt;margin-right:2.85pt;margin-bottom:
        ///  6.0pt;margin-left:18.0pt&apos;&gt;&lt;b&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana;
        ///color:red&apos;&gt;{Message}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string errorNoStackHtml {
            get {
                return ResourceManager.GetString("errorNoStackHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert range &quot;{0}&quot; to matrix. Value and formula arrays must be equal..
        /// </summary>
        internal static string ErrorRangeToMatrix {
            get {
                return ResourceManager.GetString("ErrorRangeToMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run macro &quot;{0}&quot; from non-Excel process..
        /// </summary>
        internal static string ErrorRunExcelMacroOutProc {
            get {
                return ResourceManager.GetString("ErrorRunExcelMacroOutProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=SectionMethod&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&lt;b&gt;&lt;span style=&apos;font-family:Verdana;color:#993300&apos;&gt;{ClassName}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;p class=MsoNormal style=&apos;margin-left:18.0pt&apos;&gt;&lt;span style=&apos;font-size:10.0pt;
        ///font-family:Verdana&apos;&gt;{ClassComment}&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&lt;b&gt;&lt;span style=&apos;font-family:Verdana;color:#993300&apos;&gt;&lt;a name=&quot;{FunctionName}&quot;&gt;&lt;/a&gt;{FunctionName}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelMethodHtml {
            get {
                return ResourceManager.GetString("ExcelMethodHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=MsoNormal style=&apos;margin-left:18.0pt&apos;&gt;&lt;span style=&apos;font-size:10.0pt;
        ///font-family:Verdana&apos;&gt;&lt;a href=&quot;#{FunctionName}&quot;&gt;{FunctionName}&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///.
        /// </summary>
        internal static string ExcelMethodLinkHtml {
            get {
                return ResourceManager.GetString("ExcelMethodLinkHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr size = &quot;1&quot; align=&quot;left&quot; color=&quot;#993300&quot;/&gt;
        ///
        ///&lt;br /&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&lt;b&gt;&lt;span style=&apos;font-family:Verdana;color:#993300&apos;&gt;&lt;a name =&quot;_top_&quot;&gt;ExcelApi Functions&lt;/a&gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///
        ///&lt;br /&gt;
        ///
        ///{MethodLinks}
        ///
        ///&lt;br /&gt;.
        /// </summary>
        internal static string ExcelMethodLinksHtml {
            get {
                return ResourceManager.GetString("ExcelMethodLinksHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=MsoNormal style=&apos;margin-left:18.0pt&apos;&gt;&lt;b&gt;&lt;span style=&apos;font-size:10.0pt;
        ///font-family:Verdana;color:#993300&apos;&gt;{ParamName}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;p class=MsoNormal style=&apos;margin-left:18.0pt&apos;&gt;&lt;span style=&apos;font-size:10.0pt;
        ///font-family:Verdana&apos;&gt;{ParamComment}&lt;/span&gt;&lt;/p&gt;
        ///&lt;br /&gt;.
        /// </summary>
        internal static string ExcelMethodParamHtml {
            get {
                return ResourceManager.GetString("ExcelMethodParamHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;title&gt;ExcelApi Functions&lt;/title&gt;
        ///
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:Verdana;
        ///	panose-1:2 11 6 4 3 5 4 4 2 4;}
        /// /* Style Definitions */
        /// p.MsoNormal, li.MsoNormal, div.MsoNormal
        ///	{margin:0cm;
        ///	margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;;}
        ///@page SectionMethod
        ///	{size:595.3pt 841.9pt;
        ///	margin:72.0pt 90.0pt 72.0pt 90.0pt;}
        ///div.SectionMethod
        ///	{pag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelMethodsHtml {
            get {
                return ResourceManager.GetString("ExcelMethodsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr size = &quot;1&quot; align=&quot;left&quot; color=&quot;#993300&quot;/&gt;
        ///.
        /// </summary>
        internal static string HLineHtml {
            get {
                return ResourceManager.GetString("HLineHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) to be processed. Are you sure you want to continue?.
        /// </summary>
        internal static string QuestionLoadAsmManyFiles {
            get {
                return ResourceManager.GetString("QuestionLoadAsmManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;MsoNormal&quot;&gt;
        ///  &lt;span style=&apos;font-size:10.0pt;font-family:Verdana&apos;&gt;
        ///    &lt;a href=&quot;#_top_&quot;&gt;Back to Top&lt;/a&gt;
        ///  &lt;/span&gt;
        ///&lt;/p&gt;
        ///&lt;br /&gt;
        ///.
        /// </summary>
        internal static string TopOfDocHtml {
            get {
                return ResourceManager.GetString("TopOfDocHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for parameter &quot;{1}&quot; converted to null..
        /// </summary>
        internal static string WaringExcelErrorSetNull {
            get {
                return ResourceManager.GetString("WaringExcelErrorSetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate assembly unloaded. ({0}, version {1}, build {2}).
        /// </summary>
        internal static string WarningAssemblyDisarded {
            get {
                return ResourceManager.GetString("WarningAssemblyDisarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=Section1&gt;
        ///&lt;br /&gt;
        ///&lt;p class=MsoNormal style=&apos;margin-top:6.0pt;margin-right:2.85pt;margin-bottom:
        ///6.0pt;margin-left:18.0pt&apos;&gt;&lt;b&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana;
        ///color:#FF6600&apos;&gt;{Message}&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;p class=MsoNormal style=&apos;margin-top:6.0pt;margin-right:2.85pt;margin-bottom:
        ///6.0pt;margin-left:18.0pt&apos;&gt;&lt;span style=&apos;font-size:10.0pt;font-family:Verdana&apos;&gt;{StackTrace}&lt;/span&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string WarningHtml {
            get {
                return ResourceManager.GetString("WarningHtml", resourceCulture);
            }
        }
    }
}
