//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highlander.CurveEngine.Tests.V5r3.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TenorConversion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenorConversion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Highlander.CurveEngine.Tests.V5r3.TestData.TenorConversion", typeof(TenorConversion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.999801;0.981786;0.964789;0.949085;0.933347;0.917956;0.902846;0.888466;0.873824;0.859298;0.844749;0.831545;0.817847;0.803936;0.790705;0.777707;0.764934;0.752455;0.740066;0.728166.
        /// </summary>
        internal static string Get5yqDiscountFactors {
            get {
                return ResourceManager.GetString("Get5yqDiscountFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26/08/2008;26/11/2008;26/02/2009;26/05/2009;26/08/2009;26/11/2009;26/02/2010;26/05/2010;26/08/2010;26/11/2010;28/02/2011;26/05/2011;26/08/2011;28/11/2011;27/02/2012;28/05/2012;27/08/2012;26/11/2012;26/02/2013;27/05/2013.
        /// </summary>
        internal static string Get5yqRollDates {
            get {
                return ResourceManager.GetString("Get5yqRollDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.85437;11.70246;13.67505;16.07381;16.64788;17.17488;17.40261;17.52067;17.14061;16.2994;15.70438;15.59911;15.54087;15.12467;14.81604;14.67057;14.59605;14.43131;14.19835;13.87621.
        /// </summary>
        internal static string Get5yqVols {
            get {
                return ResourceManager.GetString("Get5yqVols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26/08/2008;26/02/2009;26/08/2009;26/02/2010;26/08/2010;28/02/2011;26/08/2011;27/02/2012;27/08/2012;26/02/2013.
        /// </summary>
        internal static string Get5ysRollDates {
            get {
                return ResourceManager.GetString("Get5ysRollDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.81668;15.00831;17.05;17.60516;16.85902;15.77684;15.46703;14.86546;14.63321;14.15085.
        /// </summary>
        internal static string Get5ysVols {
            get {
                return ResourceManager.GetString("Get5ysVols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31/07/2008;29/08/2008;30/09/2008;31/10/2008;28/11/2008;31/12/2008;30/01/2009;27/02/2009;31/03/2009;30/04/2009;29/05/2009;30/06/2009;31/07/2009;31/08/2009;30/09/2009;30/10/2009;30/11/2009;31/12/2009;29/01/2010;26/02/2010;31/03/2010;30/04/2010;31/05/2010;30/06/2010;30/07/2010;31/08/2010;30/09/2010;29/10/2010;30/11/2010;31/12/2010;31/01/2011;28/02/2011;31/03/2011;29/04/2011;31/05/2011;30/06/2011;29/07/2011;31/08/2011;30/09/2011;31/10/2011;30/11/2011;30/12/2011;31/01/2012;29/02/2012;30/03/2012;30/04/2012;31/05/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMonthlyRollDates {
            get {
                return ResourceManager.GetString("GetMonthlyRollDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0;6.09521;6.77061;7.55474;8.08209;9.0419;10.28326;12.11852;12.11207;12.10973;11.82664;12.21789;12.67259;13.09066;13.55836;14.00521;14.53551;14.86184;15.1973;15.67051;15.72168;15.79672;16.03169;15.83536;15.64652;15.48516;15.23917;15.00966;14.74484;14.57694;14.415;14.15457;14.14392;14.13663;14.13347;14.1137;14.09467;14.16201;13.99775;13.851;13.63334;13.58182;13.52973;13.38238;13.46721;13.55515;13.55483;13.79576;14.00459;14.28753;14.47145;14.61556;14.92198;14.9233;14.92566;15.07394;14.87022;14.67398;14.48306 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMonthlyVols {
            get {
                return ResourceManager.GetString("GetMonthlyVols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.999801;0.980585;0.962215;0.944695;0.927418;0.910863;0.894766;0.879082;0.863755;0.84846;0.833027;0.818909;0.804636;0.789903;0.775767;0.762214;0.748626;0.735443;0.722531;0.710298;0.697909;0.685667;0.673667;0.662291;0.650758;0.639458;0.6285;0.617877;0.607229;0.596726;0.586418;0.576304;0.566378;0.55632;0.546662;0.537701;0.528196;0.519072;0.510118;0.501619.
        /// </summary>
        internal static string GetQuarterlyDiscountFactors {
            get {
                return ResourceManager.GetString("GetQuarterlyDiscountFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31/07/2008;31/10/2008;30/01/2009;30/04/2009;31/07/2009;30/10/2009;29/01/2010;30/04/2010;30/07/2010;29/10/2010;31/01/2011;29/04/2011;29/07/2011;31/10/2011;31/01/2012;30/04/2012;31/07/2012;31/10/2012;31/01/2013;30/04/2013;31/07/2013;31/10/2013;31/01/2014;30/04/2014;31/07/2014;31/10/2014;30/01/2015;30/04/2015;31/07/2015;30/10/2015;29/01/2016;29/04/2016;29/07/2016;31/10/2016;31/01/2017;28/04/2017;31/07/2017;31/10/2017;31/01/2018;30/04/2018;31/07/2018.
        /// </summary>
        internal static string GetQuarterlyRollDates {
            get {
                return ResourceManager.GetString("GetQuarterlyRollDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.82612;12.16186;12.16864;13.44969;14.81009;15.77106;15.96527;15.38966;14.68872;14.1951;14.17646;14.11025;13.6533;13.48809;13.77415;14.46835;14.98418;14.99689;14.331;13.42817;12.79745;12.2377;11.74091;11.35739;11.11962;11.05046;11.19729;11.35323;11.30283;11.24052;11.16422;11.06824;10.94534;10.80079;10.62163;10.40289;10.14464;9.85091;9.49573;0.0.
        /// </summary>
        internal static string GetQuarterlyVols {
            get {
                return ResourceManager.GetString("GetQuarterlyVols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31/07/2008;30/01/2009;31/07/2009;29/01/2010;30/07/2010;31/01/2011;29/07/2011;31/01/2012;31/07/2012;31/01/2013;31/07/2013;31/01/2014;31/07/2014;30/01/2015;31/07/2015;29/01/2016;29/07/2016;31/01/2017;31/07/2017;31/01/2018.
        /// </summary>
        internal static string GetSemiRollDates {
            get {
                return ResourceManager.GetString("GetSemiRollDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.79389;12.27736;14.25304;16.00783;15.17059;14.30854;14.01558;13.75391;14.85372;14.78618;13.22941;12.08924;11.33799;11.22032;11.4268;11.29977;11.10454;10.79972;10.36309;9.75312.
        /// </summary>
        internal static string GetSemiVols {
            get {
                return ResourceManager.GetString("GetSemiVols", resourceCulture);
            }
        }
    }
}
