//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Highlander.Metadata.Common {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd", IsNullable=false)]
    public partial class BoundaryRiderMappings {
        
        private DefaultMarketConvention[] defaultMarketConventionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DefaultMarketConvention", IsNullable=false)]
        public DefaultMarketConvention[] DefaultMarketConventions {
            get {
                return this.defaultMarketConventionsField;
            }
            set {
                this.defaultMarketConventionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd", IsNullable=false)]
    public partial class DefaultMarketConvention {
        
        private string currencyField;
        
        private string iRIndexField;
        
        private string dayCountBasisField;
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string IRIndex {
            get {
                return this.iRIndexField;
            }
            set {
                this.iRIndexField = value;
            }
        }
        
        /// <remarks/>
        public string DayCountBasis {
            get {
                return this.dayCountBasisField;
            }
            set {
                this.dayCountBasisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/BoundaryRiderMappingVals.xsd", IsNullable=false)]
    public partial class DefaultMarketConventions {
        
        private DefaultMarketConvention[] defaultMarketConventionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefaultMarketConvention")]
        public DefaultMarketConvention[] DefaultMarketConvention {
            get {
                return this.defaultMarketConventionField;
            }
            set {
                this.defaultMarketConventionField = value;
            }
        }
    }
}
