//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Metadata.Common {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/AlertFormat.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/AlertFormat.xsd", IsNullable=false)]
    public partial class AlertRule {
        
        private int priorityField;
        
        private bool disabledField;
        
        private string hostEnvNameField;
        
        private string hostComputerField;
        
        private string hostInstanceField;
        
        private string hostUserNameField;
        
        private string ruleNameField;
        
        private string dataItemTypeField;
        
        private string dataTypeNameField;
        
        private string dataSubsExprField;
        
        private string constraintField;
        
        private string conditionField;
        
        private string alertPropertiesField;
        
        private string monitorPeriodField;
        
        private string publishPeriodField;
        
        private string signalFormatField;
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string hostEnvName {
            get {
                return this.hostEnvNameField;
            }
            set {
                this.hostEnvNameField = value;
            }
        }
        
        /// <remarks/>
        public string hostComputer {
            get {
                return this.hostComputerField;
            }
            set {
                this.hostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string hostInstance {
            get {
                return this.hostInstanceField;
            }
            set {
                this.hostInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string hostUserName {
            get {
                return this.hostUserNameField;
            }
            set {
                this.hostUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        public string DataItemType {
            get {
                return this.dataItemTypeField;
            }
            set {
                this.dataItemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DataTypeName {
            get {
                return this.dataTypeNameField;
            }
            set {
                this.dataTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string DataSubsExpr {
            get {
                return this.dataSubsExprField;
            }
            set {
                this.dataSubsExprField = value;
            }
        }
        
        /// <remarks/>
        public string Constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
        
        /// <remarks/>
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string AlertProperties {
            get {
                return this.alertPropertiesField;
            }
            set {
                this.alertPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public string MonitorPeriod {
            get {
                return this.monitorPeriodField;
            }
            set {
                this.monitorPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string PublishPeriod {
            get {
                return this.publishPeriodField;
            }
            set {
                this.publishPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string SignalFormat {
            get {
                return this.signalFormatField;
            }
            set {
                this.signalFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/AlertFormat.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/AlertFormat.xsd", IsNullable=false)]
    public partial class AlertSignal {
        
        private string ruleNameField;
        
        private string alertServerField;
        
        private string statusField;
        
        private string signalMessageField;
        
        private string lastMonitoredField;
        
        /// <remarks/>
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        public string AlertServer {
            get {
                return this.alertServerField;
            }
            set {
                this.alertServerField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string SignalMessage {
            get {
                return this.signalMessageField;
            }
            set {
                this.signalMessageField = value;
            }
        }
        
        /// <remarks/>
        public string LastMonitored {
            get {
                return this.lastMonitoredField;
            }
            set {
                this.lastMonitoredField = value;
            }
        }
    }
}
