//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highlander.PublisherWebService.Tests.V5r3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Highlander.PublisherWebService.Tests.V5r3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Highlander.Market.Live.RateCurve.AUD-Swap-6M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-Swap-6M&quot;&gt;
        ///    &lt;name&gt;AUD-Swap-6M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;Swap&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;periodMultiplier&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUDSwap6M_Expected {
            get {
                return ResourceManager.GetString("AUDSwap6M_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=6M
        ///Currency/String=AUD
        ///Index/String=Swap
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUDSwap
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-15T08:54:27
        ///BaseDate/DateTime=2010-07-15T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=Live.AUDSwap.6M.Official.SydSwapDesk.15/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.Live.RateCurve.AUD-Swap-6M
        ///ExpiryIntervalInMins/Doub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUDSwap6M_Expected_Properties {
            get {
                return ResourceManager.GetString("AUDSwap6M_Expected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Highlander.Market.Live.RateCurve.AUD-Swap-6M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-Swap-6M&quot;&gt;
        ///    &lt;name&gt;AUD-Swap-6M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;Swap&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;periodMultiplier&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUDSwap6M_Input {
            get {
                return ResourceManager.GetString("AUDSwap6M_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=6M
        ///Currency/String=AUD
        ///Index/String=Swap
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUDSwap
        ///Validity/String=Official
        ///UniqueIdentifier/String=Highlander.Market.Live.RateCurve.AUD-Swap-6M
        ///Domain/String=Highlander.Market
        ///Market/String=Live
        ///.
        /// </summary>
        internal static string AUDSwap6M_Input_Properties {
            get {
                return ResourceManager.GetString("AUDSwap6M_Input_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;yieldCurve id=&quot;Live.AUDBondFuturesPay.310Y.Official.SydSwapDesk.14/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesPay-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUDBondFuturesPay&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;period [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesPay_Expected {
            get {
                return ResourceManager.GetString("BondFuturesPay_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesPay
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUDBondFuturesPay
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-14T14:40:18
        ///BaseDate/DateTime=2010-07-14T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=Live.AUDBondFuturesPay.310Y.Official.SydSwapDesk.14/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.Live.RateCurve.AUD- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesPay_Expected_Properties {
            get {
                return ResourceManager.GetString("BondFuturesPay_Expected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Highlander.Market.Live.RateCurve.AUD-BondFuturesPay-310Y&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-BondFuturesPay-310Y&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesPay-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;BondFuturesPay&lt;/floatingRateIndex&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesPay_Input {
            get {
                return ResourceManager.GetString("BondFuturesPay_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesPay
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUDBondFuturesPay
        ///Validity/String=Official
        ///UniqueIdentifier/String=Highlander.Market.Live.RateCurve.AUD-BondFuturesPay-310Y
        ///Domain/String=Highlander.Market
        ///Market/String=Live
        ///.
        /// </summary>
        internal static string BondFuturesPay_Input_Properties {
            get {
                return ResourceManager.GetString("BondFuturesPay_Input_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;yieldCurve id=&quot;Live.AUDBondFuturesRec.310Y.Official.SydSwapDesk.14/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesRec-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUD-BondFuturesRec&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;perio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesRec_Expected {
            get {
                return ResourceManager.GetString("BondFuturesRec_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesRec
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUD-BondFuturesRec
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-14T16:56:24
        ///BaseDate/DateTime=2010-07-14T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=Live.AUDBondFuturesRec.310Y.Official.SydSwapDesk.14/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.Live.RateCurve.AUD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesRec_Expected_Properties {
            get {
                return ResourceManager.GetString("BondFuturesRec_Expected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Highlander.Market.Live.RateCurve.AUD-BondFuturesRec-310Y&quot; xmlns=&quot;http://www.fpml.org/2009/FpML-4-7&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-BondFuturesRec-310Y&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesRec-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;BondFuturesRec&lt;/floatingRateIndex&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BondFuturesRec_Input {
            get {
                return ResourceManager.GetString("BondFuturesRec_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesRec
        ///Algorithm/String=Base algorithm
        ///MarketName/String=Live
        ///IndexName/String=AUD-BondFuturesRec
        ///Validity/String=Official
        ///UniqueIdentifier/String=Highlander.Market.Live.RateCurve.AUD-BondFuturesRec-310Y
        ///Domain/String=Highlander.Market
        ///Market/String=Live
        ///.
        /// </summary>
        internal static string BondFuturesRec_Input_Properties {
            get {
                return ResourceManager.GetString("BondFuturesRec_Input_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Orion.Market.Live.RateVolatilityMatrix.AUD-LIBOR-BBA-CapFloor&quot; xmlns=&quot;http://www.fpml.org/2009/FpML-4-7&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;CapFloor-AUD-SydSPU-15/07/2010&quot;&gt;
        ///    &lt;name&gt;nabCap.QR.Schemas.FpML.Currency.SydSPU.15/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapFloor_Expected {
            get {
                return ResourceManager.GetString("CapFloor_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryIntervalInMins/Double=10080
        ///MarketName/String=LPM
        ///LPMCopy/Boolean=True
        ///Source/String=SydSPU
        ///Instrument/String=CapFloor
        ///Currency/String=AUD
        ///Name/String=CapFloor-AUD-SydSPU-15/07/2010
        ///TimeState/String=LPM
        ///IndexName/String=Volatility
        ///Owner/String=SydSPU
        ///.
        /// </summary>
        internal static string CapFloor_Expected_Properties {
            get {
                return ResourceManager.GetString("CapFloor_Expected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - LpmCapFloorCurve-AUD-SydSPU-18/12/2009&quot; xmlns=&quot;http://www.fpml.org/2009/FpML-4-7&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;LpmCapFloorCurve-AUD-SydSPU-18/12/2009&quot;&gt;
        ///    &lt;name&gt;.SydSPU&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;LpmCapFloorCurve-AUD-SydSPU-18/12/2009&quot; /&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapFloor_Input {
            get {
                return ResourceManager.GetString("CapFloor_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeState/String=Highlander
        ///IndexName/String=Market
        ///Instrument/String=LPM
        ///Currency/String=LpmCapFloorCurve
        ///Owner/String=AUD-SydSPU-2009-Week50
        ///BuildDateTime/DateTime=2009-12-18T13:18:26
        ///MachineId/String=SYDWADBRL01
        ///PublisherId/String=SYDWADBRL01$
        ///Name/String=Highlander.Market.LPM.LpmCapFloorCurve.AUD-SydSPU-15/07/2010
        ///SurfaceType/String=VolatilitySurface
        ///Identifier/String=LPM.Volatility.CapFloor.AUD.SydSPU.2010.Week29.
        /// </summary>
        internal static string CapFloor_Input_Properties {
            get {
                return ResourceManager.GetString("CapFloor_Input_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///- &lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Orion.Market.Live.RateVolatilityMatrix.AUD-LIBOR-BBA-CapFloor&quot; xmlns=&quot;http://www.fpml.org/2009/FpML-4-7&quot;&gt;
        ///- &lt;volatilityRepresentation id=&quot;RateVolatilityMatrix.AUD-LIBOR-BBA-CapFloor&quot;&gt;
        ///  &lt;name&gt;AUD.CapFloor&lt;/name&gt; 
        ///  &lt;currency&gt;AUD&lt;/currency&gt; 
        ///  &lt;asset href=&quot;CapFloor&quot; /&gt; 
        ///  &lt;/volatilityRepresentation&gt;
        ///- &lt;volatilityMatrixValuation definitionRef=&quot;3M&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishCapFloorVol_Expected {
            get {
                return ResourceManager.GetString("PublishCapFloorVol_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market.Live.RateATMVolatilityMatrix.AUD-LIBOR-BBA-Swaption&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;RateATMVolatilityMatrix.AUD-LIBOR-BBA-Swaption&quot;&gt;
        ///    &lt;name&gt;AUD.Swaption&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;asset href=&quot;Swaption&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReferen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishSwaptionVol_Expected {
            get {
                return ResourceManager.GetString("PublishSwaptionVol_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - Swaption-AUD-SydSPU-15/07/2010&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;Swaption-AUD-SydSPU-15/07/2010&quot;&gt;
        ///    &lt;name&gt;nabCap.QR.Schemas.FpML.Currency.SydSPU.15/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;Swaption-AUD-SydSPU-15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Swaption_Expected {
            get {
                return ResourceManager.GetString("Swaption_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryIntervalInMins/Double=10080
        ///MarketName/String=LPM
        ///LPMCopy/Boolean=True
        ///Source/String=SydSPU
        ///Instrument/String=Swaption
        ///Currency/String=AUD
        ///Name/String=Swaption-AUD-SydSPU-15/07/2010
        ///TimeState/String=LPM
        ///IndexName/String=Volatility
        ///Owner/String=SydSPU
        ///.
        /// </summary>
        internal static string Swaption_Expected_Properties {
            get {
                return ResourceManager.GetString("Swaption_Expected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - AUD-SydSPU-15/07/2010&quot; xmlns=&quot;http://www.fpml.org/2009/FpML-4-7&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;AUD-SydSPU-15/07/2010&quot;&gt;
        ///    &lt;name&gt;.SydSPU.15/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;AUD-SydSPU-15/07/2010&quot; /&gt;
        ///    &lt;baseDate&gt;2010-07-15&lt;/baseDate&gt;
        ///    &lt;bui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Swaption_Input {
            get {
                return ResourceManager.GetString("Swaption_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=LPMSwaptionCurve
        ///Currency/String=AUD
        ///Instrument/String=Swaption
        ///Source/String=SydSPU
        ///MarketName/String=LPM
        ///IndexName/String=Volatility
        ///Index/String=LIBOR-BBA
        ///Identifier/Sring=LPM.Volatility.Swaption.AUD.SydSPU.2010.Week30.
        /// </summary>
        internal static string Swaption_Input_Properties {
            get {
                return ResourceManager.GetString("Swaption_Input_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;yieldCurve id=&quot;LiveUnitTest.AUDBondFuturesPay.310Y.Official.SydSwapDesk.16/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesPay-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUDBondFuturesPay&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudBondFuturesPay_Data {
            get {
                return ResourceManager.GetString("ValidateAudBondFuturesPay_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesPay
        ///Algorithm/String=Base algorithm
        ///MarketName/String=LiveUnitTest
        ///IndexName/String=AUDBondFuturesPay
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-16T09:20:36
        ///BaseDate/DateTime=2010-07-16T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=LiveUnitTest.AUDBondFuturesPay.310Y.Official.SydSwapDesk.16/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.Liv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudBondFuturesPay_Properties {
            get {
                return ResourceManager.GetString("ValidateAudBondFuturesPay_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;yieldCurve id=&quot;LiveUnitTest.AUDBondFuturesRec.310Y.Official.SydSwapDesk.16/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD-BondFuturesRec-310Y&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUD-BondFuturesRec&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudBondFuturesReceive_Data {
            get {
                return ResourceManager.GetString("ValidateAudBondFuturesReceive_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=310Y
        ///Currency/String=AUD
        ///Index/String=BondFuturesRec
        ///Algorithm/String=Base algorithm
        ///MarketName/String=LiveUnitTest
        ///IndexName/String=AUD-BondFuturesRec
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-16T09:20:36
        ///BaseDate/DateTime=2010-07-16T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=LiveUnitTest.AUDBondFuturesRec.310Y.Official.SydSwapDesk.16/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudBondFuturesReceive_Properties {
            get {
                return ResourceManager.GetString("ValidateAudBondFuturesReceive_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;yieldCurve id=&quot;LiveTest.AUDSwap.6M.Official.SydSwapDesk.20/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD-Swap-6M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;Base algorithm&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUDSwap&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;periodMultiplier&gt;6&lt;/periodMultiplier [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudSwap6m_Data {
            get {
                return ResourceManager.GetString("ValidateAudSwap6m_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///IndexTenor/String=6M
        ///Currency/String=AUD
        ///Index/String=Swap
        ///Algorithm/String=Base algorithm
        ///MarketName/String=LiveTest
        ///IndexName/String=AUDSwap
        ///Validity/String=Official
        ///BuildDateTime/DateTime=2010-07-20T14:20:30
        ///BaseDate/DateTime=2010-07-20T00:00:00
        ///StructureType/String=RateCurve
        ///Identifier/String=LiveTest.AUDSwap.6M.Official.SydSwapDesk.20/07/2010
        ///Domain/String=Highlander.Market
        ///DomainId/String=Highlander.Market.LiveTest.RateCurve.AUD-Swap-6M
        ///ExpiryInterva [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateAudSwap6m_Properties {
            get {
                return ResourceManager.GetString("ValidateAudSwap6m_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - CapFloor-AUD-SydSPU-20/07/2010&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;CapFloor-AUD-SydSPU-20/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD.SydSPU.20/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;CapFloor-AUD-SydSPU-20/07/2010&quot; /&gt;
        ///    &lt;baseDate&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateCapFloor_Data {
            get {
                return ResourceManager.GetString("ValidateCapFloor_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - CapFloor-AUD-SydSPU-20/07/2010&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;CapFloor-AUD-SydSPU-20/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD.SydSPU.20/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;CapFloor-AUD-SydSPU-20/07/2010&quot; /&gt;
        ///    &lt;baseDate&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateCapFloor_Data_Release {
            get {
                return ResourceManager.GetString("ValidateCapFloor_Data_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryIntervalInMins/Double=60
        ///MarketName/String=LpmTest
        ///LPMCopy/Boolean=True
        ///Source/String=SydSPU
        ///Instrument/String=CapFloor
        ///Currency/String=AUD
        ///Name/String=CapFloor-AUD-SydSPU-20/07/2010
        ///TimeState/String=LpmTest
        ///IndexName/String=Volatility
        ///Owner/String=SydSPU
        ///SurfaceType/String=VolatilitySurface
        ///.
        /// </summary>
        internal static string ValidateCapFloor_Properties {
            get {
                return ResourceManager.GetString("ValidateCapFloor_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market - Swaption-AUD-SydSPU-20/07/2010&quot; xmlns=&quot;http://www.fpml.org/2007/FpML-4-3&quot;&gt;
        ///  &lt;volatilityRepresentation id=&quot;Swaption-AUD-SydSPU-20/07/2010&quot;&gt;
        ///    &lt;name&gt;AUD.SydSPU.20/07/2010&lt;/name&gt;
        ///    &lt;asset href=&quot;Unknown&quot; /&gt;
        ///  &lt;/volatilityRepresentation&gt;
        ///  &lt;volatilityMatrixValuation&gt;
        ///    &lt;objectReference href=&quot;Swaption-AUD-SydSPU-20/07/2010&quot; /&gt;
        ///    &lt;baseDate&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateSwaption_Data {
            get {
                return ResourceManager.GetString("ValidateSwaption_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryIntervalInMins/Double=10
        ///MarketName/String=LpmTest
        ///LPMCopy/Boolean=True
        ///Source/String=SydSPU
        ///Instrument/String=Swaption
        ///Currency/String=AUD
        ///Name/String=Swaption-AUD-SydSPU-20/07/2010
        ///TimeState/String=LpmTest
        ///IndexName/String=Volatility
        ///Owner/String=SydSPU
        ///.
        /// </summary>
        internal static string ValidateSwaption_Properties {
            get {
                return ResourceManager.GetString("ValidateSwaption_Properties", resourceCulture);
            }
        }
    }
}
