//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion.V5r3.CurveGeneration.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.V5r3.CurveGeneration.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateBasisCurve
        ///Market/String=GlobalIB_EOD
        ///Currency/String=AUD
        ///CurveName/String=AUD-ZERO-BANK-1M
        ///BaseDate/DateTime=2010-10-27T00:00:00
        ///Algorithm/String=LinearSpreadZero
        ///SourceSystem/String=Orion
        ///Function/String=Market
        ///Type/String=PricingStructures
        ///Index/String=ZERO-BANK
        ///IndexTenor/String=1M
        ///ReferenceCurveUniqueId/String=Market.GlobalIB_EOD.RateCurve.AUD-BBR-BBSW-3M
        ///MarketName/String=GlobalIB_EOD
        ///Domain/String=Orion.Market
        ///UniqueIdentifier/String=Market.GlobalIB_EOD.R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_BBR_BBSW_1M_AppProps {
            get {
                return ResourceManager.GetString("AUD_BBR_BBSW_1M_AppProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market.NAB_EOD.2010-10-27.RateCurve.AUD-ZERO-BANK-1M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-ZERO-BANK-1M&quot;&gt;
        ///    &lt;name&gt;AUD-ZERO-BANK-1M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;LinearSpreadZero&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;ZERO-BANK&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_BBR_BBSW_1M_Data {
            get {
                return ResourceManager.GetString("AUD_BBR_BBSW_1M_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=RateCurve
        ///Market/String=GlobalIB_EOD
        ///Currency/String=AUD
        ///CurveName/String=AUD-BBR-BBSW-3M
        ///BaseDate/DateTime=2010-10-26T00:00:00
        ///Algorithm/String=LinearZero
        ///SourceSystem/String=Orion
        ///Function/String=Market
        ///Type/String=PricingStructures
        ///Index/String=BBR-BBSW
        ///IndexTenor/String=3M
        ///UniqueIdentifier/String=Market.GlobalIB_EOD.RateCurve.AUD-BBR-BBSW-3M
        ///Domain/String=Orion.Market
        ///MarketName/String=GlobalIB_EOD
        ///.
        /// </summary>
        internal static string AUD_BBR_BBSW_3M_AppProps {
            get {
                return ResourceManager.GetString("AUD_BBR_BBSW_3M_AppProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market.NAB_EOD.RateCurve.AUD-BBR-BBSW-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-BBR-BBSW-3M&quot;&gt;
        ///    &lt;name&gt;AUD-BBR-BBSW-3M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;LinearZero&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;BBR-BBSW&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        &lt;periodMultipl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_BBR_BBSW_3M_Data {
            get {
                return ResourceManager.GetString("AUD_BBR_BBSW_3M_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingStructureType/String=XccySpreadCurve
        ///Market/String=GlobalIB_EOD
        ///Currency/String=AUD
        ///CurveName/String=AUD-USD-BASIS
        ///BaseDate/DateTime=2010-10-28T00:00:00
        ///Algorithm/String=LinearZero
        ///SourceSystem/String=Orion
        ///Function/String=Market
        ///Type/String=PricingStructures
        ///Index/String=USD-BASIS
        ///UniqueIdentifier/String=Market.GlobalIB_EOD.RateCurve.AUD-USD-BASIS
        ///Domain/String=Orion.Market
        ///MarketName/String=GlobalIB_EOD.
        /// </summary>
        internal static string AUD_USD_BASIS_AppProps {
            get {
                return ResourceManager.GetString("AUD_USD_BASIS_AppProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market.NAB_EOD.RateCurve.AUD-USD-BASIS&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-USD-BASIS&quot;&gt;
        ///    &lt;name&gt;AUD-USD-BASIS&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;LinearZero&lt;/algorithm&gt;
        ///  &lt;/yieldCurve&gt;
        ///  &lt;yieldCurveValuation id=&quot;RateCurve.AUD-USD-BASIS&quot; definitionRef=&quot;RateSpreadCurve&quot;&gt;
        ///    &lt;baseDate&gt;2010-10-28&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_USD_BASIS_Data {
            get {
                return ResourceManager.GetString("AUD_USD_BASIS_Data", resourceCulture);
            }
        }
    }
}
