//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Highlander.Metadata.Common
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class DateRules
    {

        private DateRuleProfile[] dateRuleProfileField;

        private DateRule[] globalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRuleProfile")]
        public DateRuleProfile[] DateRuleProfile
        {
            get { return this.dateRuleProfileField; }
            set { this.dateRuleProfileField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DateRule[] Global
        {
            get { return this.globalField; }
            set { this.globalField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class DateRuleProfile
    {

        private DateRule[] dateRuleField;

        private string nameField;

        private string fPmlIdentifierField;

        private string cultureField;

        private bool enabledField;

        public DateRuleProfile()
        {
            this.enabledField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRule")]
        public DateRule[] DateRule
        {
            get { return this.dateRuleField; }
            set { this.dateRuleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fPmlIdentifier
        {
            get { return this.fPmlIdentifierField; }
            set { this.fPmlIdentifierField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string culture
        {
            get { return this.cultureField; }
            set { this.cultureField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get { return this.enabledField; }
            set { this.enabledField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class DateRule
    {

        private object itemField;

        private string nameField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private bool applyRollField;

        private bool applyRollFieldSpecified;

        private bool applyRollPriorField;

        private bool applyRollPriorFieldSpecified;

        private bool rollBeforeAfterWeekendField;

        private bool rollBeforeAfterWeekendFieldSpecified;

        private bool rollPriorIfSaturdayField;

        private bool rollPriorIfSaturdayFieldSpecified;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BasedOn", typeof(BasedOn))]
        [System.Xml.Serialization.XmlElementAttribute("Date", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("DateRuleId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DayInMonth", typeof(DayInMonth))]
        [System.Xml.Serialization.XmlElementAttribute("DayOfWeekInLastWeekOfMonth", typeof(DayOfWeekInLastWeekOfMonth))]
        [System.Xml.Serialization.XmlElementAttribute("DayOfWeekInWeekOfMonth", typeof(DayOfWeekInWeekOfMonth))]
        [System.Xml.Serialization.XmlElementAttribute("DaysAfter", typeof(DaysAfter))]
        [System.Xml.Serialization.XmlElementAttribute("EveryNMonth", typeof(EveryNMonth))]
        [System.Xml.Serialization.XmlElementAttribute("NthDayInMonth", typeof(NthDayInMonth))]
        [System.Xml.Serialization.XmlElementAttribute("WeekDayBetween", typeof(WeekDayBetween))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startDate
        {
            get { return this.startDateField; }
            set { this.startDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified
        {
            get { return this.startDateFieldSpecified; }
            set { this.startDateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endDate
        {
            get { return this.endDateField; }
            set { this.endDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified
        {
            get { return this.endDateFieldSpecified; }
            set { this.endDateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool applyRoll
        {
            get { return this.applyRollField; }
            set { this.applyRollField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applyRollSpecified
        {
            get { return this.applyRollFieldSpecified; }
            set { this.applyRollFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool applyRollPrior
        {
            get { return this.applyRollPriorField; }
            set { this.applyRollPriorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applyRollPriorSpecified
        {
            get { return this.applyRollPriorFieldSpecified; }
            set { this.applyRollPriorFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool rollBeforeAfterWeekend
        {
            get { return this.rollBeforeAfterWeekendField; }
            set { this.rollBeforeAfterWeekendField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rollBeforeAfterWeekendSpecified
        {
            get { return this.rollBeforeAfterWeekendFieldSpecified; }
            set { this.rollBeforeAfterWeekendFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RollPriorIfSaturday
        {
            get { return this.rollPriorIfSaturdayField; }
            set { this.rollPriorIfSaturdayField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RollPriorIfSaturdaySpecified
        {
            get { return this.rollPriorIfSaturdayFieldSpecified; }
            set { this.rollPriorIfSaturdayFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class BasedOn
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRuleId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("StaticFunction", typeof(StaticFunction))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class StaticFunction
    {

        private string assembleyNameField;

        private string namespaceField;

        private string classField;

        private string staticMethodField;

        /// <remarks/>
        public string AssembleyName
        {
            get { return this.assembleyNameField; }
            set { this.assembleyNameField = value; }
        }

        /// <remarks/>
        public string Namespace
        {
            get { return this.namespaceField; }
            set { this.namespaceField = value; }
        }

        /// <remarks/>
        public string Class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <remarks/>
        public string StaticMethod
        {
            get { return this.staticMethodField; }
            set { this.staticMethodField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class EveryNMonth
    {

        private object itemField;

        private int monthCycleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DayOfMonth", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DayOfWeekInWeek", typeof(DayOfWeekInWeek))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        public int MonthCycle
        {
            get { return this.monthCycleField; }
            set { this.monthCycleField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class DayOfWeekInWeek
    {

        private int dayOfWeekField;

        private int offsetBeforeField;

        private int offsetAfterField;

        private int weekOfMonthField;


        /// <remarks/>
        public int DayOfWeek
        {
            get { return this.dayOfWeekField; }
            set { this.dayOfWeekField = value; }
        }

        /// <remarks/>
        public int OffsetBefore
        {
            get { return this.offsetBeforeField; }
            set { this.offsetBeforeField = value; }
        }

        /// <remarks/>
        public int OffsetAfter
        {
            get { return this.offsetAfterField; }
            set { this.offsetAfterField = value; }
        }

        /// <remarks/>
        public int WeekOfMonth
        {
            get { return this.weekOfMonthField; }
            set { this.weekOfMonthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class DayOfWeekInLastWeekOfMonth
    {

        private int dayOfWeekField;

        private int monthField;

        /// <remarks/>
        public int DayOfWeek
        {
            get { return this.dayOfWeekField; }
            set { this.dayOfWeekField = value; }
        }

        /// <remarks/>
        public int Month
        {
            get { return this.monthField; }
            set { this.monthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class NthDayInMonth
    {

        private int instanceField;

        private int dayOfWeekField;

        private int monthField;

        /// <remarks/>
        public int Instance
        {
            get { return this.instanceField; }
            set { this.instanceField = value; }
        }

        /// <remarks/>
        public int DayOfWeek
        {
            get { return this.dayOfWeekField; }
            set { this.dayOfWeekField = value; }
        }

        /// <remarks/>
        public int Month
        {
            get { return this.monthField; }
            set { this.monthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    public partial class DayOfWeekInWeekOfMonth
    {

        private int dayOfWeekField;

        private int weekOfMonthField;

        private int monthField;

        /// <remarks/>
        public int DayOfWeek
        {
            get { return this.dayOfWeekField; }
            set { this.dayOfWeekField = value; }
        }

        /// <remarks/>
        public int WeekOfMonth
        {
            get { return this.weekOfMonthField; }
            set { this.weekOfMonthField = value; }
        }

        /// <remarks/>
        public int Month
        {
            get { return this.monthField; }
            set { this.monthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class DayInMonth
    {

        private int dayField;

        private int monthField;

        /// <remarks/>
        public int Day
        {
            get { return this.dayField; }
            set { this.dayField = value; }
        }

        /// <remarks/>
        public int Month
        {
            get { return this.monthField; }
            set { this.monthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class DaysAfter
    {

        private int noOfDaysField;

        private From fromField;

        /// <remarks/>
        public int NoOfDays
        {
            get { return this.noOfDaysField; }
            set { this.noOfDaysField = value; }
        }

        /// <remarks/>
        public From From
        {
            get { return this.fromField; }
            set { this.fromField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class From
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRuleId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DayInMonth", typeof(DayInMonth))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class WeekDayBetween
    {

        private int dayOfWeekField;

        private bool dayOfWeekFieldSpecified;

        private From fromField;

        private To toField;

        private bool inclusiveField;

        private bool inclusiveFieldSpecified;

        /// <remarks/>
        public int DayOfWeek
        {
            get { return this.dayOfWeekField; }
            set { this.dayOfWeekField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DayOfWeekSpecified
        {
            get { return this.dayOfWeekFieldSpecified; }
            set { this.dayOfWeekFieldSpecified = value; }
        }

        /// <remarks/>
        public From From
        {
            get { return this.fromField; }
            set { this.fromField = value; }
        }

        /// <remarks/>
        public To To
        {
            get { return this.toField; }
            set { this.toField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool inclusive
        {
            get { return this.inclusiveField; }
            set { this.inclusiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inclusiveSpecified
        {
            get { return this.inclusiveFieldSpecified; }
            set { this.inclusiveFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class To
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRuleId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DayInMonth", typeof(DayInMonth))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/DateRules.xsd", IsNullable = false)]
    public partial class LocationCalendarYears
    {

        private LocationCalendarYear[] locationCalendarYearField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocationCalendarYear")]
        public LocationCalendarYear[] LocationCalendarYear
        {
            get { return this.locationCalendarYearField; }
            set { this.locationCalendarYearField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("locationCalendarYear", Namespace = "http://tempuri.org/DateRules.xsd",
        IsNullable = false)]
    public partial class BusinessCenterCalendar
    {

        private string businessCenterField;

        private string locationNameField;

        private string locationField;

        private DateRule[] holidaysField;

        /// <remarks/>
        public string BusinessCenter
        {
            get { return this.businessCenterField; }
            set { this.businessCenterField = value; }
        }

        /// <remarks/>
        public string LocationName
        {
            get { return this.locationNameField; }
            set { this.locationNameField = value; }
        }

        /// <remarks/>
        public string Location
        {
            get { return this.locationField; }
            set { this.locationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Holidays")]
        public DateRule[] Holidays
        {
            get { return this.holidaysField; }
            set { this.holidaysField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/DateRules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("locationCalendarYear", Namespace = "http://tempuri.org/DateRules.xsd",
        IsNullable = false)]
    public partial class LocationCalendarYear
    {

        private string businessCenterField;

        private string locationNameField;

        private string rDMLocationField;

        private int yearField;

        private DateRule[] holidaysField;

        /// <remarks/>
        public string BusinessCenter
        {
            get { return this.businessCenterField; }
            set { this.businessCenterField = value; }
        }

        /// <remarks/>
        public string LocationName
        {
            get { return this.locationNameField; }
            set { this.locationNameField = value; }
        }

        /// <remarks/>
        public string RDMLocation
        {
            get { return this.rDMLocationField; }
            set { this.rDMLocationField = value; }
        }

        /// <remarks/>
        public int Year
        {
            get { return this.yearField; }
            set { this.yearField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Holidays")]
        public DateRule[] Holidays
        {
            get { return this.holidaysField; }
            set { this.holidaysField = value; }
        }
    }
}
