//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highlander.EquitiesCalculator.TestData.V5r3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Highlander.EquitiesCalculator.TestData.V5r3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;AGK&lt;/Name&gt;
        ///  &lt;AssetId&gt;AGK&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1350.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2001-03-26&lt;/ExDate&gt;
        ///      &lt;Amount&gt;25&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2013-03-08&lt;/ExDate&gt;
        ///      &lt;Amount&gt;33&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AGK_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("AGK_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;ANZ&lt;/Name&gt;
        ///  &lt;AssetId&gt;ANZ&lt;/AssetId&gt;
        ///  &lt;Spot&gt;2220.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2007-11-08&lt;/ExDate&gt;
        ///      &lt;Amount&gt;74&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2007-05-14&lt;/ExDate&gt;
        ///      &lt;Amount&gt;62&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ANZ_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("ANZ_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;BHP&lt;/Name&gt;
        ///  &lt;AssetId&gt;BHP&lt;/AssetId&gt;
        ///  &lt;Spot&gt;3769.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2009-08-31&lt;/ExDate&gt;
        ///      &lt;Amount&gt;47.6190476190476&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-02-20&lt;/ExDate&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BHP_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("BHP_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;BXB&lt;/Name&gt;
        ///  &lt;AssetId&gt;BXB&lt;/AssetId&gt;
        ///  &lt;Spot&gt;781.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-09-14&lt;/ExDate&gt;
        ///      &lt;Amount&gt;19&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-03-15&lt;/ExDate&gt;
        ///      &lt;Amount&gt;18&lt;/Amou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BXB_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("BXB_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;CBA&lt;/Name&gt;
        ///  &lt;AssetId&gt;CBA&lt;/AssetId&gt;
        ///  &lt;Spot&gt;4665.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2013-02-15&lt;/ExDate&gt;
        ///      &lt;Amount&gt;127&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2008-02-18&lt;/ExDate&gt;
        ///      &lt;Amount&gt;113&lt;/A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBA_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("CBA_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;CPU&lt;/Name&gt;
        ///  &lt;AssetId&gt;CPU&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1032.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2000-09-12&lt;/ExDate&gt;
        ///      &lt;Amount&gt;0.5&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2002-03-06&lt;/ExDate&gt;
        ///      &lt;Amount&gt;0.5&lt;/A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPU_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("CPU_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;CSL&lt;/Name&gt;
        ///  &lt;AssetId&gt;CSL&lt;/AssetId&gt;
        ///  &lt;Spot&gt;3393.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2003-09-22&lt;/ExDate&gt;
        ///      &lt;Amount&gt;22&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2005-08-30&lt;/ExDate&gt;
        ///      &lt;Amount&gt;10&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSL_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("CSL_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;MIG&lt;/Name&gt;
        ///  &lt;AssetId&gt;MIG&lt;/AssetId&gt;
        ///  &lt;Spot&gt;131.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-12-11&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2009-12-23&lt;/ExDate&gt;
        ///      &lt;Amount&gt;3&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2010-01-22&lt;/ExDate&gt;
        ///      &lt;Amount&gt;10&lt;/Amoun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIG_20091211 {
            get {
                return ResourceManager.GetString("MIG_20091211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;NWS&lt;/Name&gt;
        ///  &lt;AssetId&gt;NWS&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1504.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-03-06&lt;/ExDate&gt;
        ///      &lt;Amount&gt;8.13008130081301&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2013-03-06&lt;/ExDate&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NWS_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("NWS_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;ORG&lt;/Name&gt;
        ///  &lt;AssetId&gt;ORG&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1478.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2003-09-15&lt;/ExDate&gt;
        ///      &lt;Amount&gt;5&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-08-27&lt;/ExDate&gt;
        ///      &lt;Amount&gt;30&lt;/Amou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORG_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("ORG_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;RIO&lt;/Name&gt;
        ///  &lt;AssetId&gt;RIO&lt;/AssetId&gt;
        ///  &lt;Spot&gt;5818.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2001-08-13&lt;/ExDate&gt;
        ///      &lt;Amount&gt;23.2288037166086&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2006-02-22&lt;/ExDate&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RIO_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("RIO_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;SHL&lt;/Name&gt;
        ///  &lt;AssetId&gt;SHL&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1404.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2013-03-08&lt;/ExDate&gt;
        ///      &lt;Amount&gt;30&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-09-10&lt;/ExDate&gt;
        ///      &lt;Amount&gt;48&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHL_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("SHL_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;TAH&lt;/Name&gt;
        ///  &lt;AssetId&gt;TAH&lt;/AssetId&gt;
        ///  &lt;Spot&gt;710.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2001-09-03&lt;/ExDate&gt;
        ///      &lt;Amount&gt;26&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2001-03-05&lt;/ExDate&gt;
        ///      &lt;Amount&gt;25&lt;/Amou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TAH_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("TAH_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;TLS&lt;/Name&gt;
        ///  &lt;AssetId&gt;TLS&lt;/AssetId&gt;
        ///  &lt;Spot&gt;321.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2014-03-11&lt;/ExDate&gt;
        ///      &lt;Amount&gt;17.4&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2009-03-06&lt;/ExDate&gt;
        ///      &lt;Amount&gt;14&lt;/Am [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TLS_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("TLS_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;WBC&lt;/Name&gt;
        ///  &lt;AssetId&gt;WBC&lt;/AssetId&gt;
        ///  &lt;Spot&gt;2427.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2004-11-18&lt;/ExDate&gt;
        ///      &lt;Amount&gt;44&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2011-05-18&lt;/ExDate&gt;
        ///      &lt;Amount&gt;60&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WBC_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("WBC_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;WDC&lt;/Name&gt;
        ///  &lt;AssetId&gt;WDC&lt;/AssetId&gt;
        ///  &lt;Spot&gt;1266.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2013-02-04&lt;/ExDate&gt;
        ///      &lt;Amount&gt;37.5&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2009-02-02&lt;/ExDate&gt;
        ///      &lt;Amount&gt;53.25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WDC_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("WDC_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;WES&lt;/Name&gt;
        ///  &lt;AssetId&gt;WES&lt;/AssetId&gt;
        ///  &lt;Spot&gt;2554.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2000-03-20&lt;/ExDate&gt;
        ///      &lt;Amount&gt;25&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2003-03-03&lt;/ExDate&gt;
        ///      &lt;Amount&gt;42&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WES_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("WES_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;WOW&lt;/Name&gt;
        ///  &lt;AssetId&gt;WOW&lt;/AssetId&gt;
        ///  &lt;Spot&gt;2830.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2012-03-23&lt;/ExDate&gt;
        ///      &lt;Amount&gt;67&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2014-03-25&lt;/ExDate&gt;
        ///      &lt;Amount&gt;83.24&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WOW_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("WOW_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;WPL&lt;/Name&gt;
        ///  &lt;AssetId&gt;WPL&lt;/AssetId&gt;
        ///  &lt;Spot&gt;4730.000000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2008-02-25&lt;/ExDate&gt;
        ///      &lt;Amount&gt;55&lt;/Amount&gt;
        ///      &lt;PriceUnits&gt;Cents&lt;/PriceUnits&gt;
        ///    &lt;/Dividend&gt;
        ///    &lt;Dividend&gt;
        ///      &lt;ExDate&gt;2004-03-01&lt;/ExDate&gt;
        ///      &lt;Amount&gt;25&lt;/Amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WPL_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("WPL_SD_Vol_20090909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stock xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://tempuri.org/StockFormat.xsd&quot;&gt;
        ///  &lt;Name&gt;XJO&lt;/Name&gt;
        ///  &lt;AssetId&gt;XJO&lt;/AssetId&gt;
        ///  &lt;Spot&gt;4522.200000&lt;/Spot&gt;
        ///  &lt;Date&gt;2009-09-09&lt;/Date&gt;
        ///  &lt;Dividends /&gt;
        ///  &lt;RateCurve&gt;
        ///    &lt;BaseDate&gt;2009-09-09&lt;/BaseDate&gt;
        ///    &lt;Ccy&gt;AUD&lt;/Ccy&gt;
        ///    &lt;DateArray&gt;
        ///      &lt;string&gt;2009-09-10&lt;/string&gt;
        ///      &lt;string&gt;2009-10-12&lt;/string&gt;
        ///      &lt;string&gt;2009-11-10&lt;/string&gt;
        ///      &lt;st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XJO_SD_Vol_20090909 {
            get {
                return ResourceManager.GetString("XJO_SD_Vol_20090909", resourceCulture);
            }
        }
    }
}
