//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticModels.Tests.Models.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SwapResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwapResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyticModels.Tests.Models.Data.SwapResources", typeof(SwapResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/08/2008;7/11/2008;9/02/2009;7/05/2009;7/08/2009;9/11/2009;8/02/2010;7/05/2010;9/08/2010;8/11/2010;7/02/2011;9/05/2011;8/08/2011;7/11/2011;7/02/2012;7/05/2012;7/08/2012;7/11/2012;7/02/2013;7/05/2013;7/08/2013;7/11/2013;7/02/2014;7/05/2014;7/08/2014;7/11/2014;9/02/2015;7/05/2015;7/08/2015;9/11/2015;8/02/2016;9/05/2016;8/08/2016;7/11/2016;7/02/2017;8/05/2017;8/08/2017;7/11/2017;7/02/2018;7/05/2018;7/08/2018.
        /// </summary>
        internal static string GetFixedCashflowDates {
            get {
                return ResourceManager.GetString("GetFixedCashflowDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 170090.9936;170691.4838;155467.4332;161683.2391;162421.4679;154681.1085;147229.8426;154625.6738;147217.6024;144791.3672;142411.4178;140076.8972;137749.7479;136924.6277;131747.6486;132414.5066;130181.0235;127984.1094;121788.2132;123767.2337;121638.9516;119542.9056;113712.3003;115511.3014;113507.6312;113915.9178;103695.0523;107740.4718;108143.9773;102905.0813;101145.8765;99414.95745;97711.12422;97071.50421;93347.354;93762.44139;91145.56342;90540.55495;86108.19705;87454.71913.
        /// </summary>
        internal static string GetFixedCashflows {
            get {
                return ResourceManager.GetString("GetFixedCashflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.25205479;0.25753425;0.23835616;0.25205479;0.25753425;0.24931507;0.24109589;0.25753425;0.24931507;0.24931507;0.24931507;0.24931507;0.24931507;0.25205479;0.24657534;0.25205479;0.25205479;0.25205479;0.24383562;0.25205479;0.25205479;0.25205479;0.24383562;0.25205479;0.25205479;0.25753425;0.23835616;0.25205479;0.25753425;0.24931507;0.24931507;0.24931507;0.24931507;0.25205479;0.24657534;0.25205479;0.24931507;0.25205479;0.24383562;0.25205479.
        /// </summary>
        internal static string GetFixedCouponYearFractions {
            get {
                return ResourceManager.GetString("GetFixedCouponYearFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.33972603;0.59726027;0.83561644;1.08767123;1.34520548;1.59452055;1.83561644;2.09315068;2.34246575;2.59178082;2.84109589;3.09041096;3.33972603;3.59178082;3.83835616;4.09041096;4.34246575;4.59452055;4.83835616;5.09041096;5.34246575;5.59452055;5.83835616;6.09041096;6.34246575;6.60000000;6.83835616;7.09041096;7.34794521;7.59726027;7.84657534;8.09589041;8.34520548;8.59726027;8.84383562;9.09589041;9.3452054;9.59726027;9.84109589;10.09315068.
        /// </summary>
        internal static string GetFixedCurveYearFractions {
            get {
                return ResourceManager.GetString("GetFixedCurveYearFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.999801;0.98141;0.96392;0.948587;0.932898;0.917218;0.902304;0.888117;0.873194;0.858767;0.844614;0.830731;0.817113;0.803538;0.790043;0.777065;0.76402;0.751133;0.738457;0.726394;0.714126;;0.701846;0.689752;0.678226;0.66649;0.654929;0.6433;0.632697;0.621653;0.610705;0.600278;0.590016;0.579919;0.56998;0.560094;0.550575;0.541001;0.531681;0.522411;0.513584;0.504606.
        /// </summary>
        internal static string GetFixedDiscountFactors {
            get {
                return ResourceManager.GetString("GetFixedDiscountFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 358810.7279;310225.1266;305939.3087;291101.4252;285795.0122;275014.6438;270696.8415;260229.0627;255630.6997;243307.8199;243743.672;232622.5254;231900.1935;216467.0593;213748.0107;203594.5236;198251.7124;190926.5835;185903.3343;178046.2306.
        /// </summary>
        internal static string GetFloatingCashflows {
            get {
                return ResourceManager.GetString("GetFloatingCashflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5096;0.4904;0.5068;0.4986;0.4986;0.4986;0.5014;0.4986;0.5041;0.4959;0.5041;0.4959;0.5096;0.4904;0.5068;0.4986;0.5014;0.4986;0.5014;0.4959.
        /// </summary>
        internal static string GetFloatingCouponYearFractions {
            get {
                return ResourceManager.GetString("GetFloatingCouponYearFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.597260274;1.087671233;1.594520548;2.093150685;2.591780822;3.090410959;3.591780822;4.090410959;4.594520548;5.090410959;5.594520548;6.090410959;6.6;7.090410959;7.597260274;8.095890411;8.597260274;9.095890411;9.597260274;10.09315068.
        /// </summary>
        internal static string GetFloatingCurveYearFractions {
            get {
                return ResourceManager.GetString("GetFloatingCurveYearFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.96392;0.932898;0.902304;0.873194;0.844614;0.817113;0.790043;0.76402;0.738457;0.714126;0.689752;0.66649;0.6433;0.621653;0.600278;0.579919;0.560094;0.541001;0.522411;0.504606.
        /// </summary>
        internal static string GetFloatingDiscountFactors {
            get {
                return ResourceManager.GetString("GetFloatingDiscountFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.07304733;0.067808267;0.066896521;0.066858259;0.067860624;0.067498664;0.068339883;0.068308154;0.068669335;0.068706134;0.070099581;0.070383753;0.070740395;0.071004131;0.070253957;0.070407712;0.070598878;0.070776619;0.070976837;0.071153237.
        /// </summary>
        internal static string GetFloatingRates {
            get {
                return ResourceManager.GetString("GetFloatingRates", resourceCulture);
            }
        }
    }
}
