//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Orion.Contracts {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class OrdinaryCurveGenRequest : CurveGenRequest {
        
        private bool saveMarketDataField;
        
        private bool useSavedMarketDataField;
        
        private bool forceGenerateEODCurvesField;
        
        /// <remarks/>
        public bool SaveMarketData {
            get {
                return this.saveMarketDataField;
            }
            set {
                this.saveMarketDataField = value;
            }
        }
        
        /// <remarks/>
        public bool UseSavedMarketData {
            get {
                return this.useSavedMarketDataField;
            }
            set {
                this.useSavedMarketDataField = value;
            }
        }
        
        /// <remarks/>
        public bool ForceGenerateEODCurves {
            get {
                return this.forceGenerateEODCurvesField;
            }
            set {
                this.forceGenerateEODCurvesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class CurveGenRequest : RequestBase {
        
        private System.DateTime baseDateField;
        
        private CurveSelection[] curveSelectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BaseDate {
            get {
                return this.baseDateField;
            }
            set {
                this.baseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurveSelector")]
        public CurveSelection[] CurveSelector {
            get {
                return this.curveSelectorField;
            }
            set {
                this.curveSelectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class CurveSelection {

        private string nameSpaceField;
        
        private string marketNameField;
        
        private System.Nullable<System.DateTime> marketDateField;
        
        private string curveTypeField;
        
        private string curveNameField;

        /// <remarks/>
        public string NameSpace
        {
            get
            {
                return this.nameSpaceField;
            }
            set
            {
                this.nameSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string MarketName {
            get {
                return this.marketNameField;
            }
            set {
                this.marketNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> MarketDate {
            get {
                return this.marketDateField;
            }
            set {
                this.marketDateField = value;
            }
        }
        
        /// <remarks/>
        public string CurveType {
            get {
                return this.curveTypeField;
            }
            set {
                this.curveTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CurveName {
            get {
                return this.curveNameField;
            }
            set {
                this.curveNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class PortfolioSubquery {
        
        private int sequenceOrderField;
        
        private string counterpartyIdField;
        
        private string tradingBookIdField;
        
        private bool excludeItemsField;
        
        /// <remarks/>
        public int SequenceOrder {
            get {
                return this.sequenceOrderField;
            }
            set {
                this.sequenceOrderField = value;
            }
        }
        
        /// <remarks/>
        public string CounterpartyId {
            get {
                return this.counterpartyIdField;
            }
            set {
                this.counterpartyIdField = value;
            }
        }
        
        /// <remarks/>
        public string TradingBookId {
            get {
                return this.tradingBookIdField;
            }
            set {
                this.tradingBookIdField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcludeItems {
            get {
                return this.excludeItemsField;
            }
            set {
                this.excludeItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class ExceptionDetail {
        
        private string fullNameField;
        
        private string messageField;
        
        private string sourceField;
        
        private string stackTraceField;
        
        private ExceptionDetail innerErrorField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionDetail InnerError {
            get {
                return this.innerErrorField;
            }
            set {
                this.innerErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class UserIdentity {
        
        private string nameField;
        
        private string displayNameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkerAvailability))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HandlerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingWorkerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingHandlerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValuationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnassignedWorkflowRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssignedWorkflowRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancellationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TradeImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegacyCurveImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CartooCurveImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurveGenRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class WorkflowObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HandlerResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class ResponseBase : WorkflowObject {
        
        private string requestIdField;
        
        private UserIdentity requesterIdField;
        
        private string retentionField;
        
        private RequestStatusEnum statusField;
        
        private string cancelReasonField;
        
        private ExceptionDetail faultDetailField;
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public UserIdentity RequesterId {
            get {
                return this.requesterIdField;
            }
            set {
                this.requesterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string Retention {
            get {
                return this.retentionField;
            }
            set {
                this.retentionField = value;
            }
        }
        
        /// <remarks/>
        public RequestStatusEnum Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string CancelReason {
            get {
                return this.cancelReasonField;
            }
            set {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionDetail FaultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public enum RequestStatusEnum {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Received,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        Enqueued,
        
        /// <remarks/>
        Launched,
        
        /// <remarks/>
        Commencing,
        
        /// <remarks/>
        InProgress,
        
        /// <remarks/>
        Completing,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Faulted,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingWorkerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingHandlerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValuationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnassignedWorkflowRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssignedWorkflowRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancellationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TradeImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegacyCurveImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CartooCurveImportRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurveGenRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class RequestBase : WorkflowObject {

        private string requestIdField;
        
        private UserIdentity requesterIdField;
        
        private string retentionField;
        
        private string submitTimeField;
        
        private string requestDescriptionField;
        
        private bool debugEnabledField;
        
        private string runAsUsernameField;
        
        private string runAsPasswordField;
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public UserIdentity RequesterId {
            get {
                return this.requesterIdField;
            }
            set {
                this.requesterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string Retention {
            get {
                return this.retentionField;
            }
            set {
                this.retentionField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitTime {
            get {
                return this.submitTimeField;
            }
            set {
                this.submitTimeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestDescription {
            get {
                return this.requestDescriptionField;
            }
            set {
                this.requestDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool DebugEnabled {
            get {
                return this.debugEnabledField;
            }
            set {
                this.debugEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string RunAsUsername {
            get {
                return this.runAsUsernameField;
            }
            set {
                this.runAsUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string RunAsPassword {
            get {
                return this.runAsPasswordField;
            }
            set {
                this.runAsPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class PingWorkerRequest : RequestBase {
        
        private string notUsedField;
        
        /// <remarks/>
        public string NotUsed {
            get {
                return this.notUsedField;
            }
            set {
                this.notUsedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class PingHandlerRequest : RequestBase {
        
        private string delayPeriodField;
        
        private string faultMessageField;
        
        /// <remarks/>
        public string DelayPeriod {
            get {
                return this.delayPeriodField;
            }
            set {
                this.delayPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string FaultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class ValuationRequest : RequestBase {

        private string basePartyField;
        
        private System.DateTime baseDateField;
        
        private string marketNameField;
        
        private System.Nullable<System.DateTime> marketDateField;
        
        private string[] iRScenarioNamesField;
        
        private string[] fXScenarioNamesField;

        private System.DateTime[] dateScenariosField;
        
        private string reportingCurrencyField;

        private bool realTimePricingField;
        
        /// <remarks/>
        public string BaseParty {
            get {
                return this.basePartyField;
            }
            set {
                this.basePartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BaseDate {
            get {
                return this.baseDateField;
            }
            set {
                this.baseDateField = value;
            }
        }
        
        /// <remarks/>
        public string MarketName {
            get {
                return this.marketNameField;
            }
            set {
                this.marketNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> MarketDate {
            get {
                return this.marketDateField;
            }
            set {
                this.marketDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IRScenarioNames")]
        public string[] IRScenarioNames {
            get {
                return this.iRScenarioNamesField;
            }
            set {
                this.iRScenarioNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FXScenarioNames")]
        public string[] FXScenarioNames {
            get {
                return this.fXScenarioNamesField;
            }
            set {
                this.fXScenarioNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateScenarios")]
        public System.DateTime[] DateScenarios
        {
            get
            {
                return this.dateScenariosField;
            }
            set
            {
                this.dateScenariosField = value;
            }
        }
        
        /// <remarks/>
        public string ReportingCurrency {
            get {
                return this.reportingCurrencyField;
            }
            set {
                this.reportingCurrencyField = value;
            }
        }

        /// <remarks/>
        public bool RealTimePricing
        {
            get
            {
                return this.realTimePricingField;
            }
            set
            {
                this.realTimePricingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class UnassignedWorkflowRequest : RequestBase {
        
        private string requestDataTypeField;
        
        private string requestItemNameField;
        
        /// <remarks/>
        public string RequestDataType {
            get {
                return this.requestDataTypeField;
            }
            set {
                this.requestDataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestItemName {
            get {
                return this.requestItemNameField;
            }
            set {
                this.requestItemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class AssignedWorkflowRequest : RequestBase {
        
        private string workerHostComputerField;
        
        private string workerHostInstanceField;
        
        private string requestDataTypeField;
        
        private string requestItemNameField;
        
        /// <remarks/>
        public string WorkerHostComputer {
            get {
                return this.workerHostComputerField;
            }
            set {
                this.workerHostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string WorkerHostInstance {
            get {
                return this.workerHostInstanceField;
            }
            set {
                this.workerHostInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string RequestDataType {
            get {
                return this.requestDataTypeField;
            }
            set {
                this.requestDataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestItemName {
            get {
                return this.requestItemNameField;
            }
            set {
                this.requestItemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class CancellationRequest : RequestBase {
        
        private string cancelReasonField;
        
        /// <remarks/>
        public string CancelReason {
            get {
                return this.cancelReasonField;
            }
            set {
                this.cancelReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class TradeImportRequest : RequestBase {
        
        private string importDateTimeField;
        
        private string sourceSystemField;
        
        private string sourceLocationField;
        
        private string targetLocationField;
        
        private bool removeOldTargetFilesField;
        
        private bool onlyCopyUpdatedFilesField;
        
        private string copyFilePatternsField;
        
        private string fileContentTypeField;
        
        private bool revalueTradesField;
        
        /// <remarks/>
        public string ImportDateTime {
            get {
                return this.importDateTimeField;
            }
            set {
                this.importDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        public string SourceLocation {
            get {
                return this.sourceLocationField;
            }
            set {
                this.sourceLocationField = value;
            }
        }
        
        /// <remarks/>
        public string TargetLocation {
            get {
                return this.targetLocationField;
            }
            set {
                this.targetLocationField = value;
            }
        }
        
        /// <remarks/>
        public bool RemoveOldTargetFiles {
            get {
                return this.removeOldTargetFilesField;
            }
            set {
                this.removeOldTargetFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyCopyUpdatedFiles {
            get {
                return this.onlyCopyUpdatedFilesField;
            }
            set {
                this.onlyCopyUpdatedFilesField = value;
            }
        }
        
        /// <remarks/>
        public string CopyFilePatterns {
            get {
                return this.copyFilePatternsField;
            }
            set {
                this.copyFilePatternsField = value;
            }
        }
        
        /// <remarks/>
        public string FileContentType {
            get {
                return this.fileContentTypeField;
            }
            set {
                this.fileContentTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool RevalueTrades {
            get {
                return this.revalueTradesField;
            }
            set {
                this.revalueTradesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class LegacyCurveImportRequest : RequestBase {
        
        private string serverAddressField;
        
        private string marketNameField;
        
        private string marketDateField;
        
        private string otherFilterField;
        
        private bool submitStressGenRequestsField;
        
        /// <remarks/>
        public string ServerAddress {
            get {
                return this.serverAddressField;
            }
            set {
                this.serverAddressField = value;
            }
        }
        
        /// <remarks/>
        public string MarketName {
            get {
                return this.marketNameField;
            }
            set {
                this.marketNameField = value;
            }
        }
        
        /// <remarks/>
        public string MarketDate {
            get {
                return this.marketDateField;
            }
            set {
                this.marketDateField = value;
            }
        }
        
        /// <remarks/>
        public string OtherFilter {
            get {
                return this.otherFilterField;
            }
            set {
                this.otherFilterField = value;
            }
        }
        
        /// <remarks/>
        public bool SubmitStressGenRequests {
            get {
                return this.submitStressGenRequestsField;
            }
            set {
                this.submitStressGenRequestsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    public partial class CartooCurveImportRequest : RequestBase {
        
        private string importFromDateField;
        
        private bool submitStressGenRequestsField;
        
        private bool copyFilesField;
        
        /// <remarks/>
        public string ImportFromDate {
            get {
                return this.importFromDateField;
            }
            set {
                this.importFromDateField = value;
            }
        }
        
        /// <remarks/>
        public bool SubmitStressGenRequests {
            get {
                return this.submitStressGenRequestsField;
            }
            set {
                this.submitStressGenRequestsField = value;
            }
        }
        
        /// <remarks/>
        public bool CopyFiles {
            get {
                return this.copyFilesField;
            }
            set {
                this.copyFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class StressedCurveGenRequest : CurveGenRequest {
        
        private string[] stressNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StressNames")]
        public string[] StressNames {
            get {
                return this.stressNamesField;
            }
            set {
                this.stressNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class PortfolioSpecification {

        private string nameSpaceField;
        
        private string portfolioIdField;
        
        private string descriptionField;
        
        private UserIdentity ownerIdField;
        
        private PortfolioSubquery[] portfolioSubqueriesField;
        
        private string[] excludedTradeItemNamesField;
        
        private string[] includedTradeItemNamesField;
        
        private bool excludeOverridesIncludeField;

        /// <remarks/>
        public string NameSpace
        {
            get
            {
                return this.nameSpaceField;
            }
            set
            {
                this.nameSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string PortfolioId {
            get {
                return this.portfolioIdField;
            }
            set {
                this.portfolioIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public UserIdentity OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PortfolioSubqueries")]
        public PortfolioSubquery[] PortfolioSubqueries {
            get {
                return this.portfolioSubqueriesField;
            }
            set {
                this.portfolioSubqueriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludedTradeItemNames")]
        public string[] ExcludedTradeItemNames {
            get {
                return this.excludedTradeItemNamesField;
            }
            set {
                this.excludedTradeItemNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncludedTradeItemNames")]
        public string[] IncludedTradeItemNames {
            get {
                return this.includedTradeItemNamesField;
            }
            set {
                this.includedTradeItemNamesField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcludeOverridesInclude {
            get {
                return this.excludeOverridesIncludeField;
            }
            set {
                this.excludeOverridesIncludeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class TradeValuationRequest : ValuationRequest {
        
        private string tradeSourceField;
        
        private string tradeIdField;
        
        private string tradeItemNameField;
        
        /// <remarks/>
        public string TradeSource {
            get {
                return this.tradeSourceField;
            }
            set {
                this.tradeSourceField = value;
            }
        }
        
        /// <remarks/>
        public string TradeId {
            get {
                return this.tradeIdField;
            }
            set {
                this.tradeIdField = value;
            }
        }
        
        /// <remarks/>
        public string TradeItemName {
            get {
                return this.tradeItemNameField;
            }
            set {
                this.tradeItemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class PurgeValuationRequest : RequestBase {
        
        private string requesterField;
        
        private System.DateTime fromTimeField;
        
        private System.DateTime toTimeField;
        
        /// <remarks/>
        public string Requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FromTime {
            get {
                return this.fromTimeField;
            }
            set {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ToTime {
            get {
                return this.toTimeField;
            }
            set {
                this.toTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class PortfolioValuationRequest : ValuationRequest {
        
        private string portfolioIdField;
        
        /// <remarks/>
        public string PortfolioId {
            get {
                return this.portfolioIdField;
            }
            set {
                this.portfolioIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class HandlerResponse : ResponseBase {
        
        private string commenceTimeField;
        
        private string completeTimeField;
        
        private System.Nullable<int> itemCountField;
        
        private System.Nullable<int> itemsPassedField;
        
        private System.Nullable<int> itemsFailedField;
        
        /// <remarks/>
        public string CommenceTime {
            get {
                return this.commenceTimeField;
            }
            set {
                this.commenceTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CompleteTime {
            get {
                return this.completeTimeField;
            }
            set {
                this.completeTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ItemsPassed {
            get {
                return this.itemsPassedField;
            }
            set {
                this.itemsPassedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ItemsFailed {
            get {
                return this.itemsFailedField;
            }
            set {
                this.itemsFailedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class WorkerResponse : ResponseBase {
        
        private string workerHostComputerField;
        
        private string workerHostInstanceField;
        
        /// <remarks/>
        public string WorkerHostComputer {
            get {
                return this.workerHostComputerField;
            }
            set {
                this.workerHostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string WorkerHostInstance {
            get {
                return this.workerHostInstanceField;
            }
            set {
                this.workerHostInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class ManagerResponse : ResponseBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XmlContracts.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XmlContracts.xsd", IsNullable=false)]
    public partial class WorkerAvailability : WorkflowObject {
        
        private string workerHostComputerField;
        
        private string workerHostInstanceField;
        
        private int availableNodeCountField;
        
        /// <remarks/>
        public string WorkerHostComputer {
            get {
                return this.workerHostComputerField;
            }
            set {
                this.workerHostComputerField = value;
            }
        }
        
        /// <remarks/>
        public string WorkerHostInstance {
            get {
                return this.workerHostInstanceField;
            }
            set {
                this.workerHostInstanceField = value;
            }
        }
        
        /// <remarks/>
        public int AvailableNodeCount {
            get {
                return this.availableNodeCountField;
            }
            set {
                this.availableNodeCountField = value;
            }
        }
    }
}
