//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string CoreViewerForm_BtnLoadTradeClick_XML_files____xml____xml_All_files__________ {
            get {
                return ResourceManager.GetString("CoreViewerForm_BtnLoadTradeClick_XML_files____xml____xml_All_files__________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string CoreViewerForm_Form1Load__unknown_ {
            get {
                return ResourceManager.GetString("CoreViewerForm_Form1Load__unknown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string CoreViewerForm_SaveToFileToolStripMenuItemClick_Save_failed {
            get {
                return ResourceManager.GetString("CoreViewerForm_SaveToFileToolStripMenuItemClick_Save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string CoreViewerForm_SaveToFileToolStripMenuItemClick_XML_files____xml____xml {
            get {
                return ResourceManager.GetString("CoreViewerForm_SaveToFileToolStripMenuItemClick_XML_files____xml____xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important message.
        /// </summary>
        internal static string CoreViewerForm_ToolStripMenuItem1Click_Important_message {
            get {
                return ResourceManager.GetString("CoreViewerForm_ToolStripMenuItem1Click_Important_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string CoreViewerForm_TreeNavigationAfterSelect_ {
            get {
                return ResourceManager.GetString("CoreViewerForm_TreeNavigationAfterSelect_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value failed.
        /// </summary>
        internal static string CoreViewerForm_ValueStripMenuItemClick_Value_failed {
            get {
                return ResourceManager.GetString("CoreViewerForm_ValueStripMenuItemClick_Value_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string CoreViewerForm_ViewStripMenuItemClick_Properties {
            get {
                return ResourceManager.GetString("CoreViewerForm_ViewStripMenuItemClick_Properties", resourceCulture);
            }
        }
    }
}
