//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion.CurveEngine.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.CurveEngine.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Market.UnitTest.RateCurve.AUD-LIBOR-BBA-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-LIBOR-BBA-3M&quot;&gt;
        ///    &lt;name&gt;AUD-LIBOR-BBA-3M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;FastLinearZero&lt;/algorithm&gt;
        ///  &lt;/yieldCurve&gt;
        ///  &lt;yieldCurveValuation id=&quot;RateCurve.AUD-LIBOR-BBA-3M&quot; definitionRef=&quot;RateSpreadCurve&quot;&gt;
        ///    &lt;bas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_XCCY_BASIS_3M {
            get {
                return ResourceManager.GetString("AUD_XCCY_BASIS_3M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Orion.Market.EOD.RateCurve.AUD-XCCY-BASIS-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-XCCY-BASIS-3M&quot;&gt;
        ///    &lt;name&gt;AUD-XCCY-BASIS-3M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;LinearZero&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;AUD-XCCY-BASIS&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_XCCY_BASIS_3M_2010_07_06 {
            get {
                return ResourceManager.GetString("AUD_XCCY_BASIS_3M_2010_07_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;Orion.Market.UnitTest.RateCurve.AUD-LIBOR-BBA-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///  &lt;yieldCurve id=&quot;RateCurve.AUD-LIBOR-BBA-3M&quot;&gt;
        ///    &lt;name&gt;AUD-LIBOR-BBA-3M&lt;/name&gt;
        ///    &lt;currency&gt;AUD&lt;/currency&gt;
        ///    &lt;algorithm&gt;FastLinearZero&lt;/algorithm&gt;
        ///    &lt;forecastRateIndex&gt;
        ///      &lt;floatingRateIndex&gt;LIBOR-BBA&lt;/floatingRateIndex&gt;
        ///      &lt;indexTenor&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_XCCY_BASIS_3M_Adjusted {
            get {
                return ResourceManager.GetString("AUD_XCCY_BASIS_3M_Adjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;RateCurve.AUD-ZERO-BANK-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///	&lt;yieldCurve id=&quot;RateCurve.AUD-ZERO-BANK-3M&quot;&gt;
        ///		&lt;name&gt;AUD-LIBOR-BBA-3M&lt;/name&gt;
        ///		&lt;currency&gt;AUD&lt;/currency&gt;
        ///		&lt;algorithm&gt;FastLinearZero&lt;/algorithm&gt;
        ///		&lt;forecastRateIndex&gt;
        ///			&lt;floatingRateIndex&gt;AUD-LIBOR-BBA&lt;/floatingRateIndex&gt;
        ///			&lt;indexTenor&gt;
        ///				&lt;periodMultiplier&gt;3&lt;/periodMultiplie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUD_ZERO_BANK_3M {
            get {
                return ResourceManager.GetString("AUD_ZERO_BANK_3M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;market xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; id=&quot;RateCurve.AUD-ZERO-BANK-3M&quot; xmlns=&quot;http://www.fpml.org/FpML-5/reporting&quot;&gt;
        ///	&lt;yieldCurve id=&quot;RateCurve.AUD-ZERO-BANK-3M&quot;&gt;
        ///		&lt;name&gt;USD-LIBOR-BBA-3M&lt;/name&gt;
        ///		&lt;currency&gt;USD&lt;/currency&gt;
        ///		&lt;algorithm&gt;FastLinearZero&lt;/algorithm&gt;
        ///		&lt;forecastRateIndex&gt;
        ///			&lt;floatingRateIndex&gt;USD-LIBOR-BBA&lt;/floatingRateIndex&gt;
        ///			&lt;indexTenor&gt;
        ///				&lt;periodMultiplier&gt;3&lt;/periodMultiplie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USD_ZERO_BANK_3M {
            get {
                return ResourceManager.GetString("USD_ZERO_BANK_3M", resourceCulture);
            }
        }
    }
}
